import { z } from 'zod';
import { supportsEfficiency } from '../equipment-efficiency/index.ts';
import type { Project } from '../contracts/index.ts';
const number = z.number().finite().nonnegative();
const positive = z.number().finite().positive();
const fraction = z.number().finite().min(0).max(1);
const efficiency = z.number().finite().gt(0).lte(1);
const station = z.object({ batteries: positive.int().max(500), capacityKWh: positive.max(5000), readySOC: fraction, returnSOC: fraction, bays: positive.int().max(100), swapMinutes: positive.min(.1), guns: positive.int().max(100), gunKW: positive, chargePoolKW: positive, batteryChargeKW: positive, auxiliaryKW: number }).refine(s => s.readySOC > s.returnSOC, 'Ready SOC must exceed return SOC');
const row = z.object({ day:number.int().max(30), hour: number.int().max(23), station: z.enum(['A', 'B']), swapCount: number.int().max(1000), swapKWh: number, chargeCount: number.int().max(1000), chargeKWh: number, idleRaw: number.nullable(), gridPrice: number, swapFee: number, chargeFee: number, swapTotalRaw: number, chargeTotalRaw: number }).refine(r => (r.swapCount > 0 || r.swapKWh === 0) && (r.chargeCount > 0 || r.chargeKWh === 0), 'Energy requires a nonzero session count');
export const serviceRowSchema=row;
export const projectSchema = z.object({ schemaVersion: z.literal('1.3'), horizonDays: positive.int().max(31), moneyPolicy: z.literal('CNY_CENT_HALF_UP'), equipmentSchedule: z.array(z.object({atMinute:number,equipmentId:z.string().min(1),enabled:z.boolean()})).max(1000), engineering: z.object({ profile: z.literal('SUPPLEMENT_513'), pcsSlotsPerSite: number.int().max(8), intertie: z.boolean(), simultaneity: efficiency, packVoltage: positive.max(1000), passengerSlots: number.int().min(14).max(30), passengerSwapSeconds: positive, passengerChargerKW: number, passengerAuxKW: number, passengerLoadFactor: fraction, truckAuxLoadFactor: fraction }).optional(), name: z.string().min(1).max(120), seed: number.int().max(4294967295), phase: z.union([z.literal(1), z.literal(2)]), mode: z.enum(['SOURCE_REPLAY', 'CONSTRAINED']), strategy: z.enum(['IMMEDIATE', 'TOU']), arrival: z.enum(['SCHEDULED', 'SEEDED']), topology: z.object({ nodes: z.array(z.object({ id: z.string().min(1), type: z.string(), name: z.string().min(1).max(120).refine(v=>v.trim().length>0), station: z.enum(['A', 'B']), x: z.number().finite(), y: z.number().finite(), enabled: z.boolean(), params: z.record(number) })).min(1).max(500), edges: z.array(z.object({ id: z.string(), source: z.string(), target: z.string(), enabled: z.boolean() })).max(1000) }), services: z.array(row).min(48).max(1488), station: z.object({ A: station, B: station }), efficiency: z.object({ mode: z.enum(['SOURCE_CHAIN', 'ASSEMBLY']), sst: efficiency, transformer: efficiency, pcs: efficiency, charger: efficiency, sstSource: efficiency, pcsSource: efficiency }), billing: z.enum(['EXACT_COMPONENTS', 'SOURCE_DISPLAY_PRICE']), finance: z.object({ capex: number.max(1e10).nullable(), fixedDaily: number.max(1e10).nullable(), variablePerKWh: number.max(1e6), discountRate: z.number().finite().min(0).max(1), years: positive.int().max(30), rampMonths: number.int().max(120), startLoad: fraction, operatingDaysPerYear: positive.max(366) }), sources: z.array(z.object({ id: z.string(), status: z.string(), note: z.string() })) }).superRefine((p, ctx) => {
 for(const n of p.topology.nodes)if(n.params.efficiency!==undefined&&(!supportsEfficiency(n.type)||n.params.efficiency<=0||n.params.efficiency>1||p.efficiency.mode!=='ASSEMBLY'))ctx.addIssue({code:z.ZodIssueCode.custom,message:`${n.id}: 個別效率須在 (0,1]，僅支援轉換設備且須使用設備組裝模式`}); if(p.engineering && (p.engineering.pcsSlotsPerSite>p.station.A.batteries || p.engineering.pcsSlotsPerSite>p.station.B.batteries || p.station.A.batteries>32 || p.station.B.batteries>32 || p.station.A.guns>16 || p.station.B.guns>16)) ctx.addIssue({code:z.ZodIssueCode.custom,message:'詳細互動案例支援每側最多32電池倉、16槍，PCS倉數不得超過電池倉數'}); for(const event of p.equipmentSchedule){if(event.atMinute>=p.horizonDays*1440||!p.topology.nodes.some(n=>n.id===event.equipmentId))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Invalid equipment availability event'});} const keys = new Set(p.services.map(r => `${r.station}:${r.day}:${r.hour}`)); if (keys.size !== p.horizonDays*48 || p.services.length !== p.horizonDays*48 || p.services.some(r=>r.day>=p.horizonDays))
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Each station must have 24 unique hours for each day in the horizon' }); if (p.services.reduce((sum, r) => sum + r.swapCount + r.chargeCount, 0) > 20000)
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Interactive simulation supports at most 20,000 requests' }); });
export function parseProject(input: unknown): Project { return projectSchema.parse(input); }
export function migrateProject(input: unknown): Project { const p = structuredClone(input) as Record<string, unknown>; if (p.schemaVersion === '1.0') {
    p.schemaVersion = '1.1';
    p.arrival ??= 'SCHEDULED';
    p.sources ??= [];
} if (p.schemaVersion === '1.1') p.schemaVersion = '1.2'; if(p.schemaVersion==='1.2'){p.schemaVersion='1.3';p.horizonDays??=1;p.moneyPolicy??='CNY_CENT_HALF_UP';p.equipmentSchedule??=[];p.services=(p.services as Record<string,unknown>[]).map(r=>({day:0,...r}));} return parseProject(p); }
