import test from 'node:test';
import assert from 'node:assert/strict';
import {ServiceFleet,energyAtSOC,socAtEnergy,type FleetConfig} from '../packages/service-fleet/index.ts';
import {parseFleetDraft} from '../packages/service-fleet/validation.ts';
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function setup():FleetConfig{return {swaps:[{id:'A-truck',station:'A',kind:'truck-swap',enabled:true,bays:1,swapMinutes:7.5,readySOC:1,slots:[{id:'A-rack-0',sink:'A-rack-0',battery:{id:'initial',family:'truck',capacityKWh:513,soh:.8,initialSOC:1},chargeKW:560,chargeEfficiency:1}]}],guns:[],profiles:[],swapArrivals:[{id:'arrival',fleetId:'A-truck',atMinute:0,returnSOC:null,requestedKWh:410.4,minReturnSOC:.2,unitPrice:.8,returnedPack:null}],chargeArrivals:[]};}
function run(config:FleetConfig,end=1440){const f=new ServiceFleet(config);f.activate();let t=0;while(t<end-1e-8){const power=Object.fromEntries(f.powerRequests().map(r=>[r.id,r.kw])),next=f.nextEventMinute(power,end);assert.ok(next>t);f.advance(next,power);f.activate(next);t=next;}return f;}
test('absolute hourly energy never silently rescales under SOH and preserves impossible requested energy',()=>{const f=run(setup());const t=f.snapshot().transactions[0];close(t.requestedKWh!,410.4);assert.equal(t.start,null);assert.equal(t.completion,null);close(t.deliveredKWh,0);close(f.snapshot().totals.inventoryResidualKWh,0);});
test('absolute feasible request pairs with actual SOH and computes returned energy',()=>{const c=setup();c.swapArrivals[0].requestedKWh=300;const f=run(c,7.5),t=f.snapshot().transactions[0],b=f.batteryStates()[0];close(t.requestedKWh!,300);close(t.deliveredKWh,300);close(b.energyKWh,110.4);close(b.soc,110.4/410.4);close(b.remainingKWh,300);close(f.snapshot().totals.inventoryResidualKWh,0);});
test('explicit SOC mode remains capacity/SOH based and rejects conflicting absolute truths',()=>{const c=setup();delete c.swapArrivals[0].requestedKWh;delete c.swapArrivals[0].minReturnSOC;c.swapArrivals[0].returnSOC=.2;close(run(c,7.5).snapshot().transactions[0].deliveredKWh,328.32);c.swapArrivals[0].requestedKWh=300;c.swapArrivals[0].minReturnSOC=.2;assert.throws(()=>new ServiceFleet(c),/TWO_ENERGY_TRUTHS/);});
test('SOC taper splits exactly; zero power band pauses without phantom charging',()=>{const c=setup();c.swapArrivals=[];const slot=c.swaps[0].slots[0];slot.battery={...slot.battery,capacityKWh:100,soh:1,initialSOC:0};slot.chargeEfficiency=.8;slot.chargeBands=[{fromSOC:0,toSOC:.5,voltageV:500,maxKW:100,maxCurrentA:100},{fromSOC:.5,toSOC:1,voltageV:500,maxKW:0,maxCurrentA:100}];const f=new ServiceFleet(c);f.activate();const p=Object.fromEntries(f.powerRequests().map(r=>[r.id,r.kw]));close(p['battery:A-truck:A-rack-0'],50);close(f.nextEventMinute(p,1000),75);assert.throws(()=>f.advance(76,p),/ADVANCE_CROSSES_EVENT/);f.advance(75,p);f.activate();close(f.batteryStates()[0].soc,.5);close(f.powerRequests()[0].kw,0);f.advance(200,{'battery:A-truck:A-rack-0':0});close(f.batteryStates()[0].soc,.5);close(f.snapshot().totals.batteryLossKWh,12.5);});
test('energy-SOC map has an exact inverse and affects stored energy, target and hourly pairing',()=>{const c=setup();const map=[{soc:0,energyFraction:0},{soc:.5,energyFraction:.4},{soc:1,energyFraction:1}];c.swaps[0].readySOC=.9;c.swaps[0].slots[0].battery.initialSOC=.9;c.swaps[0].slots[0].battery.energySOC=map;c.swapArrivals[0].requestedKWh=250;const full=energyAtSOC(513,.8,.9,map);close(full,361.152);for(const soc of [0,.1,.2,.5,.7,.9,1])close(socAtEnergy(513,.8,energyAtSOC(513,.8,soc,map),map),soc);const f=run(c,7.5),b=f.batteryStates()[0];close(b.energyKWh,full-250);close(b.soc,socAtEnergy(513,.8,full-250,map));close(b.targetEnergyKWh,full);close(b.remainingKWh,250);assert.deepEqual(b.energySOC,map);});
test('explicit returned pack uses its own model; absence of curve means linear',()=>{const c=setup();c.swaps[0].slots[0].battery.energySOC=[{soc:0,energyFraction:0},{soc:.5,energyFraction:.4},{soc:1,energyFraction:1}];c.swapArrivals[0]={...c.swapArrivals[0],requestedKWh:null,minReturnSOC:null,returnSOC:.5,returnedPack:{id:'returned-linear',family:'truck',capacityKWh:100,soh:1,initialSOC:.5}};const f=run(c,7.5),b=f.batteryStates()[0];close(b.energyKWh,50);close(b.soc,.5);assert.equal(b.energySOC,null);});
test('nullable measurement drafts save; incomplete or non-monotone curves block execution',()=>{const c=setup();const s=c.swaps[0].slots[0];s.battery.energySOC=[{soc:0,energyFraction:0},{soc:.5,energyFraction:null},{soc:1,energyFraction:1}];assert.deepEqual(parseFleetDraft(c),c);assert.throws(()=>new ServiceFleet(c),/ENERGY_SOC_MONOTONE/);s.battery.energySOC=[{soc:0,energyFraction:0},{soc:.5,energyFraction:.8},{soc:.8,energyFraction:.7},{soc:1,energyFraction:1}];assert.throws(()=>new ServiceFleet(c),/ENERGY_SOC_MONOTONE/);s.battery.energySOC=null;s.chargeBands=[{fromSOC:0,toSOC:1,voltageV:null,maxKW:null,maxCurrentA:null}];assert.deepEqual(parseFleetDraft(c),c);assert.throws(()=>new ServiceFleet(c),/MISSING_OR_INVALID/);});
test('unreserved per-slot request state reflects full, disabled and charging conditions',()=>{const c=setup();c.swapArrivals=[];const f=new ServiceFleet(c);f.activate();const full=f.batteryStates()[0];close(full.soc,1);close(full.remainingKWh,0);close(full.requestedKW,0);f.activate(0,{disabledSinks:['A-rack-0'],pausedFleetIds:['A-truck']});const disabled=f.batteryStates()[0];assert.equal(disabled.enabled,false);assert.equal(disabled.operating,false);close(disabled.soc,1);});

test('returned battery identity cannot duplicate another resident pack and rejection is atomic',()=>{const c=setup();c.swaps[0].slots.push({...structuredClone(c.swaps[0].slots[0]),id:'A-rack-1',sink:'A-rack-1',battery:{id:'already-resident',family:'truck',capacityKWh:513,soh:.8,initialSOC:1}});c.swapArrivals[0]={...c.swapArrivals[0],requestedKWh:null,minReturnSOC:null,returnSOC:.2,returnedPack:{id:'already-resident',family:'truck',capacityKWh:513,soh:.8,initialSOC:.2}};const f=new ServiceFleet(c);f.activate();f.advance(7.5,{});const before=f.snapshot();assert.throws(()=>f.activate(),/DUPLICATE_RESIDENT_BATTERY/);assert.deepEqual(f.snapshot(),before);});
