import test from 'node:test';
import assert from 'node:assert/strict';
import {flowBoundary} from '../packages/flow-boundary/index.ts';
import {flowView,createPowerTrace,recordPowerTrace} from '../packages/power-trace/index.ts';
import {makeNode} from '../plugins/equipment/index.ts';
import {engineeringProject} from '../packages/engineering/index.ts';
import {defaultDetailedConfig} from '../packages/detailed-model/defaults.ts';
import {storageStep} from '../packages/physical-models/index.ts';
import type {RunResult} from '../packages/contracts/index.ts';
const close=(a:number|null,b:number,tol=1e-8)=>assert.ok(a!==null&&Math.abs(a-b)<tol,`${a} != ${b}`);
function runStub(){const p=engineeringProject();p.detailed=defaultDetailedConfig(p);p.detailed.storage=[];p.topology={nodes:[],edges:[]};return {engineVersion:'test',parameterSnapshot:p,mode:'CONSTRAINED',hours:[],transactions:[],diagnostics:[],componentEnergy:[],edgeEnergy:[],sourceMeters:[],totals:{initialStoredKWh:0,finalStoredKWh:0},detailedResult:{serviceEvents:[],storage:[],electrical:[],pv:[],exports:[],switching:[],inventory:[],energy:{}}} as unknown as RunResult;}
function storage(run:RunResult,{energy=80,input=12,output=0,etaC=.9,etaD=1,lambda=.02,calendar=0,minutes=1}={}){const config={enabled:true,capacityKWh:100,minSOC:0,maxSOC:1,chargeKW:100,dischargeKW:100,chargeEfficiency:etaC,dischargeEfficiency:etaD,selfDischargePerHour:lambda,calendarFadePerDay:calendar,cycleFadePerEquivalentCycle:0};const store={id:'s',station:'A' as const,kind:'ESS' as const,connectionNodeId:'bus',config,initialSOC:energy/100,initialSOH:1,policy:{mode:'MANUAL' as const,chargeBelow:null,dischargeAbove:null,reserveSOC:0,manualKW:input-output}};run.parameterSnapshot.detailed!.storage=[store];let state={energyKWh:energy,soh:1,equivalentCycles:0};for(let t=0;t<minutes;t++){const next=storageStep(config,state,input,output,1/60);run.detailedResult!.storage.push({fromMinute:t,toMinute:t+1,id:'s',station:'A',initialStoredKWh:state.energyKWh,inputKW:input,outputKW:output,inputKWh:next.inputKWh,outputKWh:next.outputKWh,lossKWh:next.lossKWh,selfDischargeKWh:next.selfDischargeKWh,capacitySpillKWh:next.capacitySpillKWh,storedKWh:next.state.energyKWh,deltaKWh:next.storageDeltaKWh,soh:next.state.soh,cycles:next.state.equivalentCycles});state=next.state;}return store;}
function trace(run:RunResult,nodes:[string,string,number,number,number,number][],links:[string,string,number][],end=1){const p=run.parameterSnapshot;p.topology.nodes=nodes.map(([id,type])=>makeNode(type,id,'A',0,0,{kw:1000,kva:1000,pf:1,amps:1000,voltage:800}));p.topology.edges=links.map(([source,target])=>({id:`${source}>${target}`,source,target,enabled:true}));const tr=createPowerTrace(p);tr.endMinute=end;recordPowerTrace(tr,p,0,new Map(nodes.map(([id,_,input,output,loss,terminal])=>[id,{input,output,loss,terminal}])),new Map(links.map(([a,b,q])=>[`${a}>${b}`,q])),new Map(),new Set(),new Set());run.powerTrace=tr;}
test('graph treats PV and storage as source ports; external boundary excludes storage',()=>{const r=runStub();storage(r,{input:0,output:5,etaC:1});trace(r,[['grid','grid',10,10,0,0],['pv','pv-source',20,20,0,0],['s-source','storage-source',5,5,0,0],['converter','charger',35,32,3,0],['service','ac-load',30,30,0,30],['export','grid-export',2,2,0,2]],[['grid','converter',10],['pv','converter',20],['s-source','converter',5],['converter','service',30],['converter','export',2]]);const view=flowView(r,0,'power');close(view.grid,10);close(view.sourceInput!,35);close(view.pvInput!,20);close(view.storageInput!,5);close(view.maxResidual,0);for(const id of ['grid','pv','s-source'])close(view.nodes.find(n=>n.id===id)!.connectionResidual,0);const b=flowBoundary(r,view);close(b.externalInput,30);close(b.storageWithdrawal,5);close(b.export,2);close(b.serviceTerminal,30);close(b.selfDischarge,1.6);close(b.storageDelta,-6.6);close(b.externalResidual,0);});
test('subminute storage state and decay match independent Decimal65 values',()=>{const r=runStub();storage(r);trace(r,[['grid','grid',12,12,0,0],['in','storage-converter',12,10.8,1.2,0],['sink','storage-sink',10.8,10.8,0,10.8]],[['grid','in',12],['in','sink',10.8]]);const b=flowBoundary(r,flowView(r,.75,'cumulative',.25));assert.equal(b.issues.length,0);close(b.grid,.1);close(b.storage[0].initialStoredKWh,80.03833173615548);close(b.storage[0].finalStoredKWh,80.11498562619784);close(b.storage[0].conversionLoss,.01);close(b.selfDischarge,.01334610995763567);close(b.storageDelta,.07665389004236433);close(b.externalResidual,0);close(b.storage[0].balanceResidual,0);const late=flowBoundary(r,flowView(r,.75,'power'));close(late.selfDischarge,.02*80.11498562619784);close(late.externalResidual,0);});
test('capacity spill uses post-event endpoints, remains additive, and is never flattened into power',()=>{const r=runStub();storage(r,{energy:100,input:0,etaC:1,lambda:.001,calendar:.24,minutes:2});trace(r,[],[],2);const full=flowBoundary(r,flowView(r,2,'cumulative',0)),left=flowBoundary(r,flowView(r,1,'cumulative',0)),right=flowBoundary(r,flowView(r,2,'cumulative',1)),window=flowBoundary(r,flowView(r,1.5,'cumulative',.5));close(full.selfDischarge,.003333027780246900);close(full.capacitySpillKWh,.030000305553086433);close(full.totalLoss,.033333333333333333);close(full.externalResidual,0);close(full.totalLoss,left.totalLoss+right.totalLoss);close(full.storageDelta,left.storageDelta+right.storageDelta);close(window.storage[0].initialStoredKWh,99.99916667013888);close(window.storage[0].finalStoredKWh,99.98250014236053);close(window.selfDischarge,.001666513889544751);close(window.capacitySpillKWh,.015000013888811729);close(window.externalResidual,0);const before=flowBoundary(r,flowView(r,1-1e-7,'cumulative',0));close(before.capacitySpillKWh,0);const at=flowBoundary(r,flowView(r,1,'power'));close(at.passiveLoss,.001*99.98333333333333);close(at.capacitySpillKWh,.015000013888811729);close(at.externalResidual,0);const empty=flowBoundary(r,flowView(r,1,'cumulative',1));close(empty.totalLoss,0);close(empty.storageDelta,0);});
test('operating account separately replaces rack replenishment with swap delivery plus inventory delta',()=>{const r=runStub();trace(r,[['grid','grid',15,15,0,0],['rack','rack',10,10,0,10],['gun','gun',3,3,0,3],['aux','ac-load',2,2,0,2]],[['grid','rack',10],['grid','gun',3],['grid','aux',2]],60);const zero={station:'A' as const,serviceKind:'truck-swap' as const,batteryLossKWh:0,outgoingKWh:0,returnedKWh:0,revenueDelta:0};r.detailedResult!.serviceEvents=[{...zero,atMinute:0,toMinute:60,kind:'battery-charge',terminalKWh:10,storedChangeKWh:10,deliveredKWh:0},{...zero,atMinute:0,toMinute:60,kind:'charge-energy',serviceKind:'direct-charge',terminalKWh:3,storedChangeKWh:0,deliveredKWh:3},{...zero,atMinute:30,kind:'swap-complete',terminalKWh:0,outgoingKWh:8,returnedKWh:1,storedChangeKWh:-7,deliveredKWh:7}];const full=flowBoundary(r,flowView(r,60,'cumulative',0)),left=flowBoundary(r,flowView(r,30,'cumulative',0)),right=flowBoundary(r,flowView(r,60,'cumulative',30));assert.ok(full.operating?.available);close(full.serviceTerminal,15);close(full.operating!.swapDeliveredKWh,7);close(full.operating!.directDeliveredKWh,3);close(full.operating!.swapBatteryDeltaKWh,3);close(full.operating!.auxiliaryKWh,2);close(full.operating!.balanceResidualKWh,0);close(left.operating!.swapDeliveredKWh,0);close(right.operating!.swapDeliveredKWh,7);close(full.operating!.swapBatteryDeltaKWh,left.operating!.swapBatteryDeltaKWh+right.operating!.swapBatteryDeltaKWh);});
test('missing interval endpoints do not invent an operating ledger',()=>{const r=runStub();trace(r,[],[],60);r.detailedResult!.serviceEvents=[{atMinute:0,station:'A',kind:'battery-charge',serviceKind:'truck-swap',terminalKWh:1,batteryLossKWh:0,storedChangeKWh:1,outgoingKWh:0,returnedKWh:0,deliveredKWh:0,revenueDelta:0}];const b=flowBoundary(r,flowView(r,1,'cumulative',.25));assert.equal(b.operating!.available,false);assert.match(b.operating!.reason!,/區間終點/);});
test('missing enabled-storage ledger makes the site boundary unavailable instead of assuming zero passive loss',()=>{const r=runStub();storage(r);r.detailedResult!.storage=[];trace(r,[],[],1);const b=flowBoundary(r,flowView(r,.5,'cumulative',0));assert.equal(b.available,false);assert.equal(b.externalResidual,null);assert.ok(b.issues.some(i=>i.includes('缺少儲能帳本')));});

import {detailedVerificationProjects} from '../packages/detailed-verification/index.ts';
import {simulateDetailed} from '../packages/detailed-model/engine.ts';
test('actual multiday detailed engine agrees with full and subminute operational flow boundaries',()=>{for(const {project} of detailedVerificationProjects()){const run=simulateDetailed(project),end=project.horizonDays*1440;for(const [from,to]of [[0,end],[0,7.5],[7.5,127.25],[719.75,1140.25],[1439.5,1507.5],[end-0.75,end]]){const b=flowBoundary(run,flowView(run,to,'cumulative',from));assert.equal(b.available,true);close(b.networkResidual,0,1e-6);close(b.externalResidual,0,1e-6);assert.ok(b.operating?.available);close(b.operating!.balanceResidualKWh,0,1e-6);}const b=flowBoundary(run,flowView(run,end,'cumulative',0));close(b.grid,run.totals.gridKWh,1e-6);close(b.totalLoss,run.totals.lossKWh,1e-6);close(b.operating!.swapDeliveredKWh+b.operating!.directDeliveredKWh,run.totals.deliveredKWh,1e-6);}});
