import test from 'node:test';
import assert from 'node:assert/strict';
import {ServiceFleet,type FleetConfig,type PowerRequest,type AllocatedPower} from '../packages/service-fleet/index.ts';
import {parseFleetDraft} from '../packages/service-fleet/validation.ts';
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const empty=():FleetConfig=>({swaps:[],profiles:[],guns:[],swapArrivals:[],chargeArrivals:[]});
function run(c:FleetConfig,end:number,allocate:(requests:PowerRequest[])=>AllocatedPower=rs=>Object.fromEntries(rs.map(r=>[r.id,r.kw]))){const fleet=new ServiceFleet(c);let t=0,terminal=0;fleet.activate(0);while(t<end-1e-8){const requests=fleet.powerRequests(),power=allocate(requests),next=fleet.nextEventMinute(power,Math.min(end,(Math.floor(t/60)+1)*60));assert.ok(next>t);terminal+=Object.values(power).reduce((a,b)=>a+b,0)*(next-t)/60;fleet.advance(next,power);fleet.activate(next);t=next;}return {fleet,state:fleet.snapshot(),terminal};}
function slotConfig(kind:'truck-swap'|'passenger-swap'='passenger-swap'):FleetConfig{const c=empty();c.swaps.push({id:'A-fleet',station:'A',kind,enabled:true,bays:1,swapMinutes:7.5,readySOC:1,slots:[{id:'slot-1',sink:'A-rack',battery:{id:'initial-pack',family:'TEST',capacityKWh:100,soh:1,initialSOC:1},chargeKW:50,chargeEfficiency:1}]});return c;}
function arrival(id:string,t:number){return {id,station:'A' as const,atMinute:t,unitPrice:1,gunsRequired:1 as const,energyKWh:100,profileId:null,initialSOC:null,targetSOC:null,temperatureC:null,temperatureSchedule:[],allowedGunIds:null};}
test('passenger 3 days exact events, charge inventory and revenue',()=>{const c=slotConfig();c.swapArrivals=Array.from({length:3},(_,d)=>({id:`swap-${d}`,fleetId:'A-fleet',atMinute:d*1440+540,returnSOC:0,unitPrice:.8,returnedPack:null}));const {state,terminal}=run(c,4320);close(terminal,300);close(state.totals.swapDeliveredKWh,300);close(state.totals.revenue,240);close(state.totals.initialStoredKWh,100);close(state.totals.finalStoredKWh,100);close(state.totals.inventoryResidualKWh,0);assert.equal(state.totals.completed,3);assert.deepEqual(state.transactions.map(t=>t.completion),[547.5,1987.5,3427.5]);});
test('shared DD 4 days: replenishment and external gun compete for one 50 kW limit',()=>{const c=slotConfig('truck-swap');c.guns.push({id:'gun-1',sink:'A-dd-external-gun',station:'A',terminal:'A-terminal',enabled:true,maxKW:50,maxCurrentA:600,maxVoltageV:1000});for(let d=0;d<4;d++){c.swapArrivals.push({id:`swap-${d}`,fleetId:'A-fleet',atMinute:d*1440,returnSOC:0,unitPrice:.8,returnedPack:null});c.chargeArrivals.push(arrival(`charge-${d}`,d*1440+7.5));}const {state,terminal}=run(c,5760,rs=>{const total=rs.reduce((a,r)=>a+r.kw,0);return Object.fromEntries(rs.map(r=>[r.id,r.kw*Math.min(1,50/(total||1))]));});close(terminal,800);close(state.totals.swapDeliveredKWh,400);close(state.totals.directTerminalKWh,400);close(state.totals.revenue,720);close(state.totals.finalStoredKWh,100);close(state.totals.inventoryResidualKWh,0);assert.equal(state.totals.completed,8);assert.deepEqual(state.transactions.filter(t=>t.kind==='direct-charge').map(t=>t.completion),[247.5,1687.5,3127.5,4567.5]);});
test('5-day dual guns, SOC taper, current and temperature limits split exact boundaries',()=>{const c=empty();c.profiles.push({id:'vehicle',enabled:true,capacityKWh:100,soh:1,chargeEfficiency:.8,bands:[{fromSOC:0,toSOC:.5,voltageV:500,maxKW:100,maxCurrentA:200},{fromSOC:.5,toSOC:1,voltageV:500,maxKW:50,maxCurrentA:200}],temperatureBands:[{minC:-20,maxC:0,multiplier:.5},{minC:0,maxC:60,multiplier:1}]});for(let i=0;i<2;i++)c.guns.push({id:`gun-${i}`,sink:`A-gun-${i}`,station:'A',terminal:'pair',enabled:true,maxKW:100,maxCurrentA:100,maxVoltageV:1000});for(let d=0;d<5;d++)c.chargeArrivals.push({...arrival(`charge-${d}`,d*1440),gunsRequired:2,energyKWh:null,profileId:'vehicle',initialSOC:0,targetSOC:1,temperatureC:20});const {fleet,state,terminal}=run(c,7200);close(terminal,625);close(state.totals.directStoredKWh,500);close(state.totals.directBatteryLossKWh,125);close(state.totals.revenue,625);assert.equal(state.totals.completed,5);for(let d=0;d<5;d++)close(state.transactions[d].completion!,d*1440+112.5);assert.deepEqual(state.transactions[0].gunIds,['gun-0','gun-1']);const firstHalf=fleet.events().filter(e=>e.kind==='charge-energy'&&e.atMinute<37.5);close(firstHalf.reduce((v,e)=>v+e.terminalKWh,0),62.5);});
test('per returned pack capacity and SOH preserve outgoing/returned/inventory energy',()=>{const c=slotConfig();c.swapArrivals=[{id:'swap',fleetId:'A-fleet',atMinute:0,returnSOC:.25,unitPrice:1,returnedPack:{id:'returned',family:'TEST',capacityKWh:100,soh:.8,initialSOC:.25}}];const {state,terminal}=run(c,1440);close(state.totals.outgoingKWh,100);close(state.totals.returnedKWh,20);close(state.totals.swapDeliveredKWh,80);close(terminal,60);close(state.totals.finalStoredKWh,80);close(state.totals.inventoryResidualKWh,0);assert.equal(state.batteries[0].batteryId,'returned');close(state.batteries[0].soh,.8);});
test('battery absorption efficiency is separate from DD efficiency',()=>{const c=slotConfig();c.swaps[0].slots[0].battery.initialSOC=0;c.swaps[0].slots[0].chargeEfficiency=.8;const {state,terminal}=run(c,1440);close(terminal,125);close(state.totals.batteryLossKWh,25);close(state.totals.finalStoredKWh,100);close(state.totals.inventoryResidualKWh,0);});
test('nullable disabled CATL draft saves, readiness blocks enabled missing values, strict unknown rejects',()=>{const c=empty();c.swaps.push({id:'catl',station:'A',kind:'passenger-swap',enabled:false,bays:null,swapMinutes:99/60,readySOC:null,slots:[]});assert.deepEqual(parseFleetDraft(JSON.parse(JSON.stringify(c))),c);new ServiceFleet(c);c.swaps[0].enabled=true;assert.throws(()=>new ServiceFleet(c),/MISSING_OR_INVALID/);assert.throws(()=>parseFleetDraft({...c,unexpected:1}),/DRAFT_UNKNOWN/);assert.throws(()=>parseFleetDraft({...c,swaps:'bad'}),/DRAFT_ARRAY/);});
test('advance cannot cross an exact completion and allocation rejection is atomic',()=>{const c=slotConfig();c.swaps[0].slots[0].battery.initialSOC=0;const f=new ServiceFleet(c);f.activate();const before=f.snapshot();assert.throws(()=>f.advance(121,{'battery:A-fleet:slot-1':50}),/ADVANCE_CROSSES_EVENT/);assert.deepEqual(f.snapshot(),before);assert.throws(()=>f.advance(1,{'battery:A-fleet:slot-1':51}),/ALLOCATION_EXCEEDS/);assert.deepEqual(f.snapshot(),before);});
test('a dual-gun request cannot claim guns on different terminals',()=>{const c=empty();for(let i=0;i<2;i++)c.guns.push({id:`gun-${i}`,sink:`A-gun-${i}`,station:'A',terminal:`separate-${i}`,enabled:true,maxKW:100,maxCurrentA:600,maxVoltageV:1000});c.chargeArrivals.push({...arrival('dual',0),gunsRequired:2});const {state,terminal}=run(c,60);close(terminal,0);assert.equal(state.transactions[0].start,null);assert.equal(state.totals.completed,0);});

test('light station state and connector efficiency map match full snapshot',()=>{const c=slotConfig();c.swaps[0].slots[0].chargeEfficiency=.9;const f=new ServiceFleet(c);f.activate();assert.deepEqual(f.stationState('A'),{storedKWh:100,ready:1,queue:0,activeSwaps:0,activeCharges:0});assert.deepEqual(f.stationState('B'),{storedKWh:0,ready:0,queue:0,activeSwaps:0,activeCharges:0});assert.deepEqual(f.slotEtaMap(),{'A-rack':.9});});
test('profile service skips an incompatible voltage gun instead of occupying it indefinitely',()=>{const c=empty();c.profiles.push({id:'vehicle',enabled:true,capacityKWh:100,soh:1,chargeEfficiency:1,bands:[{fromSOC:0,toSOC:1,voltageV:500,maxKW:100,maxCurrentA:200}],temperatureBands:null});c.guns.push({id:'bad',sink:'bad',station:'A',terminal:'bad',enabled:true,maxKW:100,maxCurrentA:600,maxVoltageV:400},{id:'good',sink:'good',station:'A',terminal:'good',enabled:true,maxKW:100,maxCurrentA:600,maxVoltageV:1000});c.chargeArrivals.push({...arrival('profile',0),energyKWh:null,profileId:'vehicle',initialSOC:0,targetSOC:1});const {state}=run(c,120);assert.deepEqual(state.transactions[0].gunIds,['good']);close(state.transactions[0].completion!,60);});
