import type {Project,RunResult,HourResult,Transaction,StationId,ServiceRow,ComponentEnergy,EdgeEnergy,SourceMeter} from '../contracts/index.ts';
import {SeededRandom} from '../sim-kernel/index.ts';
import {allocatePower,outputCapacity} from '../electrical-engine/index.ts';
import {bill} from '../economics-engine/index.ts';
import {invoiceCents,apportionCents,sumMoney} from '../money/index.ts';
import {validateTopology,sourceDiagnostics} from '../topology-engine/index.ts';
import {createPowerTrace,recordPowerTrace} from '../power-trace/index.ts';
import {parseProject} from '../schemas/index.ts';
const ids:StationId[]=['A','B'];const EPS=1e-8;
export const ENGINE_VERSION='0.5.0';
const blank=(r:ServiceRow):HourResult=>({day:r.day,hour:r.hour,station:r.station,requestedKWh:r.swapKWh+r.chargeKWh,deliveredKWh:0,swapCount:0,chargeCount:0,gridKWh:0,lossKWh:0,auxiliaryKWh:0,revenue:0,gridCost:0,auxiliaryGridCost:0,ready:0,queue:0,storedKWh:0,balanceResidual:0,peakKW:0});
function finish(p:Project,hours:HourResult[],transactions:Transaction[],initial:number,final:number,diagnostics:RunResult['diagnostics'],componentEnergy:ComponentEnergy[]=[],edgeEnergy:EdgeEnergy[]=[],sourceMeters:SourceMeter[]=[]):RunResult{
 const sum=(key:keyof HourResult)=>hours.reduce((a,h)=>a+Number(h[key]),0),delivered=sum('deliveredKWh'),requested=sum('requestedKWh');
 return {engineVersion:ENGINE_VERSION,parameterSnapshot:structuredClone(p),mode:p.mode,hours,transactions,diagnostics,componentEnergy,edgeEnergy,sourceMeters,totals:{deliveredKWh:delivered,requestedKWh:requested,gridKWh:sum('gridKWh'),lossKWh:sum('lossKWh'),revenue:p.mode==='SOURCE_REPLAY'?sum('revenue'):sumMoney(hours.map(h=>h.revenue)),gridCost:sumMoney(hours.map(h=>h.gridCost)),auxiliaryGridCost:sumMoney(hours.map(h=>h.auxiliaryGridCost)),completed:sum('swapCount')+sum('chargeCount'),unservedKWh:Math.max(0,requested-delivered),initialStoredKWh:initial,finalStoredKWh:final,maxBalanceResidual:Math.max(...hours.map(h=>Math.abs(h.balanceResidual)),...componentEnergy.map(n=>n.maxBalanceResidual))}};
}
export function replay(input:Project):RunResult{const p=parseProject(input);p.mode='SOURCE_REPLAY';return finish(p,p.services.map(r=>({...blank(r),deliveredKWh:r.swapKWh+r.chargeKWh,swapCount:r.swapCount,chargeCount:r.chargeCount,revenue:bill(r,'swap',r.swapKWh,p.billing)+bill(r,'charge',r.chargeKWh,p.billing)})),[],0,0,sourceDiagnostics(p));}
interface Battery{energy:number;reserved:boolean;index:number;}
interface ActiveSwap{job:Transaction;battery:Battery;remaining:number;}
interface State{batteries:Battery[];swapQueue:Transaction[];chargeQueue:Transaction[];charging:Transaction[];swapping:ActiveSwap[];}
interface Request{sink:string;kw:number;station:StationId;kind:'aux'|'battery'|'gun'|'legacy';index:number;}
export function simulate(input:Project):RunResult{
 const p=parseProject(input);if(p.mode==='SOURCE_REPLAY')return replay(p);const snapshot=structuredClone(p),horizon=p.horizonDays*1440;
 const diagnostics=[...validateTopology(p.topology),...sourceDiagnostics(p)];if(diagnostics.some(d=>d.severity==='error'))throw Error(diagnostics.filter(d=>d.severity==='error').map(d=>d.message).join('\n'));
 for(const s of ids)if(!p.engineering&&!p.topology.nodes.some(n=>n.id===`${s}-charger`&&n.type==='charger'))throw Error(`Missing station sink: ${s}-charger`);
 if(p.engineering&&p.efficiency.mode!=='ASSEMBLY')throw Error('詳細多分支供電需使用設備組裝效率模式');
 if(p.engineering)diagnostics.push({code:'PASSENGER_LOAD_ONLY',severity:'warning',message:'CATL站作共用交流負載；沒有乘用車換電收入。'});
 const rows=new Map(p.services.map(r=>[`${r.station}:${r.day*24+r.hour}`,r])),hours=p.services.map(blank),hourly=new Map(hours.map(h=>[`${h.station}:${h.day*24+h.hour}`,h]));
 const index=(t:number)=>Math.max(0,Math.min(p.horizonDays*24-1,Math.floor((t+1e-8)/60)));
 const getHour=(s:StationId,t:number)=>hourly.get(`${s}:${index(t)}`)!,rate=(s:StationId,t:number)=>rows.get(`${s}:${index(t)}`)!;
 const state=(s:StationId):State=>({batteries:Array.from({length:p.station[s].batteries},(_,index)=>({index,energy:p.station[s].capacityKWh*p.station[s].readySOC,reserved:false})),swapQueue:[],chargeQueue:[],charging:[],swapping:[]});
 const states={A:state('A'),B:state('B')},stored=(s:StationId)=>states[s].batteries.reduce((v,b)=>v+b.energy,0),initial={A:stored('A'),B:stored('B')};
 const availableRack=(s:StationId,b:Battery)=>!p.engineering||p.topology.nodes.some(n=>n.id===`${s}-rack-${b.index}`&&n.enabled);
 const ready=(s:StationId)=>states[s].batteries.filter(b=>!b.reserved&&availableRack(s,b)&&b.energy>=p.station[s].capacityKWh*p.station[s].readySOC-EPS).length;
 const rng=new SeededRandom(p.seed),transactions:Transaction[]=[];let ordinal=0;
 for(const row of p.services)for(const kind of ['swap','charge'] as const){const count=kind==='swap'?row.swapCount:row.chargeCount,energy=kind==='swap'?row.swapKWh:row.chargeKWh;for(let i=0;i<count;i++){const arrival=row.day*1440+row.hour*60+(p.arrival==='SEEDED'?rng.next()*60:i*60/count);const unitPrice=p.billing==='SOURCE_DISPLAY_PRICE'?(kind==='swap'?row.swapTotalRaw:row.chargeTotalRaw):row.gridPrice+(kind==='swap'?row.swapFee:row.chargeFee);transactions.push({id:`${row.station}-${row.day}-${row.hour}-${kind}-${ordinal++}`,station:row.station,kind,arrival,start:null,completion:null,requestedKWh:energy/count,deliveredKWh:0,unitPrice,revenue:0});}}
 const arrivals=[...transactions].sort((a,b)=>a.arrival-b.arrival);let arrivalCursor=0;
 const schedule=[...p.equipmentSchedule].sort((a,b)=>a.atMinute-b.atMinute);let scheduleCursor=0;
 for(const s of ids){const energy=p.station[s].capacityKWh*(p.station[s].readySOC-p.station[s].returnSOC);if(transactions.some(j=>j.station===s&&j.kind==='swap'&&Math.abs(j.requestedKWh-energy)>1e-6))diagnostics.push({code:'SWAP_ENERGY_MISMATCH',severity:'warning',message:`${s} 需求與 SOC 窗口 ${energy} kWh 不符，無法配對的請求保留排隊。`});}
 const components=new Map<string,ComponentEnergy>(),edges=new Map<string,EdgeEnergy>(),meters=new Map<string,SourceMeter>();
 const powerTrace=createPowerTrace(p);
 const costWeights=new Map<string,Map<string,number>>();let t=0,steps=0;const warned=new Set<string>();
 function recognize(job:Transaction,energy:number,time:number){job.deliveredKWh+=energy;const cents=invoiceCents(job.deliveredKWh,job.unitPrice!);const h=getHour(job.station,time);h.deliveredKWh+=energy;h.revenue+=(cents-Math.round((job.revenue??0)*100))/100;job.revenue=cents/100;}
 function completeSwaps(time:number){for(const s of ids){const st=states[s];for(const active of st.swapping.filter(a=>a.remaining<EPS)){active.battery.energy=p.station[s].capacityKWh*p.station[s].returnSOC;active.battery.reserved=false;active.job.completion=time;recognize(active.job,active.job.requestedKWh,time);getHour(s,time).swapCount++;}st.swapping=st.swapping.filter(a=>a.remaining>=EPS);}}
 while(t<horizon-EPS){if(++steps>2000000)throw Error('STEP_LIMIT_EXCEEDED');completeSwaps(t);
  let topologyChanged=false;while(scheduleCursor<schedule.length&&schedule[scheduleCursor].atMinute<=t+EPS){topologyChanged=true;const event=schedule[scheduleCursor++];p.topology.nodes.find(n=>n.id===event.equipmentId)!.enabled=event.enabled;}
  if(topologyChanged){const errors=validateTopology(p.topology).filter(d=>d.severity==='error');if(errors.length)throw Error(`SCHEDULE_TOPOLOGY:${t}:`+errors.map(d=>d.code+':'+d.message).join(';'));}
  while(arrivalCursor<arrivals.length&&arrivals[arrivalCursor].arrival<=t+EPS){const job=arrivals[arrivalCursor++];(job.kind==='swap'?states[job.station].swapQueue:states[job.station].chargeQueue).push(job);}
  const auxRequests:Request[]=[];for(const s of ids){const c=p.engineering;if(c){auxRequests.push({sink:`${s}-passenger`,kw:(c.passengerChargerKW+c.passengerAuxKW)*c.passengerLoadFactor,station:s,kind:'aux',index:0},{sink:`${s}-swap-bay`,kw:p.station[s].auxiliaryKW*c.truckAuxLoadFactor,station:s,kind:'aux',index:0},{sink:`${s}-sst-aux`,kw:p.topology.nodes.filter(n=>n.station===s&&n.type==='sst'&&n.enabled).length*10,station:s,kind:'aux',index:0});}else auxRequests.push({sink:p.topology.nodes.some(n=>n.id===`${s}-aux`)?`${s}-aux`:`${s}-grid`,kw:p.station[s].auxiliaryKW,station:s,kind:'aux',index:0});}
  const support=allocatePower(p,auxRequests),blocked=new Set<string>(),operating={A:true,B:true};
  auxRequests.forEach((r,i)=>{if(support[i].delivered+1e-6<r.kw){if(r.sink.endsWith('sst-aux'))for(const n of p.topology.nodes.filter(n=>n.station===r.station&&n.type==='sst'))blocked.add(n.id);if(r.sink.endsWith('swap-bay')||!p.engineering)operating[r.station]=false;const code=`AUX_SHORTFALL:${r.sink}`;if(!warned.has(code)){warned.add(code);diagnostics.push({code:'AUX_SHORTFALL',severity:'warning',message:`${r.sink} 必要輔助供電不足；相依設備停機或暫停作業。`});}}});
  for(const s of ids)if(p.engineering&&!p.topology.nodes.some(n=>n.id===`${s}-swap-bay`&&n.enabled))operating[s]=false;
  const powerProject={...p,topology:{...p.topology,nodes:p.topology.nodes.map(n=>blocked.has(n.id)?{...n,enabled:false}:n)}};
  for(const s of ids){const st=states[s],c=p.station[s];while(operating[s]&&st.swapping.length<c.bays&&st.swapQueue.length){const jobIndex=st.swapQueue.findIndex(j=>Math.abs(j.requestedKWh-c.capacityKWh*(c.readySOC-c.returnSOC))<=1e-6);if(jobIndex<0)break;const job=st.swapQueue[jobIndex];const b=st.batteries.find(b=>!b.reserved&&availableRack(s,b)&&b.energy>=c.capacityKWh*c.readySOC-EPS);if(!b)break;st.swapQueue.splice(jobIndex,1);b.reserved=true;job.start=t;st.swapping.push({job,battery:b,remaining:c.swapMinutes});}
   while(st.charging.length<c.guns&&st.chargeQueue.length){const free=Array.from({length:c.guns},(_,i)=>`${s}-gun-${i}`).find(id=>(!p.engineering||p.topology.nodes.some(n=>n.id===id&&n.enabled))&&!st.charging.some(j=>j.equipmentId===id));if(!free)break;const job=st.chargeQueue.shift()!;job.start=t;job.equipmentId=free;st.charging.push(job);}
  }
  const demands=ids.map(s=>{const st=states[s],c=p.station[s],canCharge=p.strategy==='IMMEDIATE'||rate(s,t).gridPrice<.7||ready(s)<Math.max(2,c.bays*2);const batteries=st.batteries.map(b=>!b.reserved&&canCharge&&availableRack(s,b)&&b.energy<c.capacityKWh*c.readySOC-EPS?c.batteryChargeKW:0),ev=st.charging.map(j=>j.deliveredKWh<j.requestedKWh-EPS?c.gunKW:0),evTotal=ev.reduce((a,b)=>a+b,0),f=evTotal?Math.min(1,c.chargePoolKW/evTotal):0;return {s,batteries,ev:ev.map(v=>v*f),kw:batteries.reduce((a,b)=>a+b,0)+evTotal*f};});
  const requests=[...auxRequests];for(const d of demands)if(p.engineering){d.batteries.forEach((kw,index)=>requests.push({sink:`${d.s}-rack-${index}`,kw,station:d.s,kind:'battery',index}));d.ev.forEach((kw,index)=>requests.push({sink:states[d.s].charging[index].equipmentId!,kw,station:d.s,kind:'gun',index}));}else requests.push({sink:`${d.s}-charger`,kw:d.kw,station:d.s,kind:'legacy',index:0});
  const allocations=allocatePower(powerProject,requests),bp:{A:number[];B:number[]}={A:[],B:[]},gp:{A:number[];B:number[]}={A:[],B:[]};
  requests.forEach((r,i)=>{const a=allocations[i];if(r.kind==='battery')bp[r.station][r.index]=a.delivered;if(r.kind==='gun')gp[r.station][r.index]=a.delivered;if(r.kind==='legacy'){const d=demands.find(d=>d.s===r.station)!,f=d.kw?a.delivered/d.kw:0;bp[r.station]=d.batteries.map(v=>v*f);gp[r.station]=d.ev.map(v=>v*f);}});
  let next=Math.min(horizon,Math.floor(t+EPS)+1,arrivals[arrivalCursor]?.arrival??Infinity,schedule[scheduleCursor]?.atMinute??Infinity);
  for(const s of ids){const st=states[s];if(operating[s])for(const a of st.swapping)next=Math.min(next,t+a.remaining);st.batteries.forEach((b,i)=>{if((bp[s][i]??0)>EPS)next=Math.min(next,t+60*(p.station[s].capacityKWh*p.station[s].readySOC-b.energy)/bp[s][i]);});st.charging.forEach((j,i)=>{if((gp[s][i]??0)>EPS)next=Math.min(next,t+60*(j.requestedKWh-j.deliveredKWh)/gp[s][i]);});}
  if(next<=t+1e-10)throw Error('NON_ADVANCING_SCHEDULER');const dt=(next-t)/60,hi=index(t),day=Math.floor(hi/24),hour=hi%24;
  const nodeStep=new Map<string,{input:number;output:number;loss:number;terminal:number}>(),edgeStep=new Map<string,number>(),sourceStep=new Map<string,number>(),consumerPeak={A:0,B:0};
  requests.forEach((r,i)=>{const a=allocations[i],h=getHour(r.station,t);h.gridKWh+=a.grid*dt;h.lossKWh+=a.loss*dt;consumerPeak[r.station]+=a.grid;if(r.kind==='aux')h.auxiliaryKWh+=a.delivered*dt;
   for(const [source,kw] of Object.entries(a.sourceImport)){sourceStep.set(source,(sourceStep.get(source)??0)+kw);const key=`${hi}:${source}`,weights=costWeights.get(key)??new Map<string,number>(),consumer=`${r.station}:${r.kind==='aux'?'aux':'traffic'}`;weights.set(consumer,(weights.get(consumer)??0)+kw*dt);costWeights.set(key,weights);}
   for(const f of a.nodeFlows){const n=nodeStep.get(f.nodeId)??{input:0,output:0,loss:0,terminal:0};n.input+=f.inputKW;n.output+=f.outputKW;n.loss+=f.lossKW;n.terminal+=f.terminalKW;nodeStep.set(f.nodeId,n);}for(const f of a.edgeFlows)edgeStep.set(f.edgeId,(edgeStep.get(f.edgeId)??0)+f.kw);
  });
  const requestedPower=new Map<string,number>();for(const r of requests)requestedPower.set(r.sink,(requestedPower.get(r.sink)??0)+r.kw);
  const auxiliaryShortfall=new Set(auxRequests.filter((r,i)=>support[i].delivered+1e-6<r.kw).map(r=>r.sink));
  recordPowerTrace(powerTrace,p,t,nodeStep,edgeStep,requestedPower,blocked,auxiliaryShortfall);
  for(const [id,n] of nodeStep){const node=powerProject.topology.nodes.find(v=>v.id===id)!,key=`${hi}:${id}`,record=components.get(key)??{day,hour,nodeId:id,inputKWh:0,outputKWh:0,lossKWh:0,terminalKWh:0,peakOutputKW:0,capacityKW:outputCapacity(powerProject,node),maxBalanceResidual:0};record.inputKWh+=n.input*dt;record.outputKWh+=n.output*dt;record.lossKWh+=n.loss*dt;record.terminalKWh+=n.terminal*dt;record.peakOutputKW=Math.max(record.peakOutputKW,n.output);const out=p.topology.edges.filter(e=>e.source===id).reduce((sum,e)=>sum+(edgeStep.get(e.id)??0),0);record.maxBalanceResidual=Math.max(record.maxBalanceResidual,Math.abs(n.input-n.output-n.loss)*dt,Math.abs(n.output-out-n.terminal)*dt,node.type==='grid'?0:Math.abs(n.input-p.topology.edges.filter(e=>e.target===id).reduce((sum,e)=>sum+(edgeStep.get(e.id)??0),0))*dt);if(record.maxBalanceResidual>1e-6)throw Error('COMPONENT_BALANCE:'+id);if(n.output>record.capacityKW+1e-6)throw Error('COMPONENT_CAPACITY_EXCEEDED:'+id);components.set(key,record);}
  for(const [id,kw] of edgeStep){const edge=p.topology.edges.find(e=>e.id===id)!,key=`${hi}:${id}`,record=edges.get(key)??{day,hour,edgeId:id,source:edge.source,target:edge.target,kWh:0,peakKW:0};record.kWh+=kw*dt;record.peakKW=Math.max(record.peakKW,kw);edges.set(key,record);}
  for(const [id,kw] of sourceStep){const key=`${hi}:${id}`,station=p.topology.nodes.find(n=>n.id===id)!.station,record=meters.get(key)??{day,hour,sourceId:id,importKWh:0,peakKW:0,unitPrice:rate(station,t).gridPrice,cost:0};record.importKWh+=kw*dt;record.peakKW=Math.max(record.peakKW,kw);meters.set(key,record);}
  for(const s of ids){const st=states[s],h=getHour(s,t);h.peakKW=Math.max(h.peakKW,consumerPeak[s]);st.batteries.forEach((b,i)=>{b.energy=Math.min(p.station[s].capacityKWh*p.station[s].readySOC,b.energy+(bp[s][i]??0)*dt);});st.charging.forEach((j,i)=>{const energy=Math.min(j.requestedKWh-j.deliveredKWh,(gp[s][i]??0)*dt);recognize(j,energy,t);if(j.deliveredKWh>=j.requestedKWh-EPS){j.completion=next;getHour(s,next).chargeCount++;}});st.charging=st.charging.filter(j=>j.completion===null);if(operating[s])for(const a of st.swapping)a.remaining=Math.max(0,a.remaining-(next-t));}
  t=next;if(Math.abs(t/60-Math.round(t/60))<1e-8)for(const s of ids){const h=getHour(s,t-1e-6);h.storedKWh=stored(s);h.ready=ready(s);h.queue=states[s].swapQueue.length+states[s].chargeQueue.length;}
 }
 completeSwaps(horizon);for(const s of ids){const h=getHour(s,horizon);h.storedKWh=stored(s);h.ready=ready(s);h.queue=states[s].swapQueue.length+states[s].chargeQueue.length;}
 for(const [key,m] of meters){const cents=invoiceCents(m.importKWh,m.unitPrice);m.cost=cents/100;const entries=[...(costWeights.get(key)??new Map()).entries()].sort((a,b)=>a[0].localeCompare(b[0])),parts=apportionCents(cents,entries.map(e=>e[1]));entries.forEach(([consumer],i)=>{const [s,kind]=consumer.split(':'),h=hourly.get(`${s}:${m.day*24+m.hour}`)!;h.gridCost+=parts[i]/100;if(kind==='aux')h.auxiliaryGridCost+=parts[i]/100;});}
 for(const s of ids){let before=initial[s];for(let hour=0;hour<p.horizonDays*24;hour++){const h=hourly.get(`${s}:${hour}`)!;h.revenue=Math.round(h.revenue*100)/100;h.gridCost=Math.round(h.gridCost*100)/100;h.auxiliaryGridCost=Math.round(h.auxiliaryGridCost*100)/100;h.balanceResidual=h.gridKWh-h.lossKWh-h.auxiliaryKWh-h.deliveredKWh-(h.storedKWh-before);before=h.storedKWh;if(Math.abs(h.balanceResidual)>.000001)throw Error(`ENERGY_BALANCE:${s}:${hour}:${h.balanceResidual}`);}}
 const result=finish(snapshot,hours,transactions,initial.A+initial.B,stored('A')+stored('B'),diagnostics,[...components.values()],[...edges.values()],[...meters.values()]);
 result.powerTrace=powerTrace;
 if(result.totals.finalStoredKWh<result.totals.initialStoredKWh-.01)result.diagnostics.push({code:'ENDING_INVENTORY',severity:'warning',message:'期末庫存能源低於期初；代表日不具能源持續性，停止投資回報外推。'});
 return result;
}
