"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Button} from '../ui/button';
import {Input} from '../ui/input';
import {Switch} from '../ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '../ui/table';
import {Choice} from './controls';
import type {Project} from '../../packages/contracts/index.ts';
import type {DetailedConfig} from '../../packages/detailed-model/contracts.ts';
import {defaultDetailedConfig,syncCostInventory} from '../../packages/detailed-model/defaults.ts';
import {appendDetailedTemplate,hasDetailedTemplate,prepareBatterySlotParameters} from '../../packages/detailed-model/templates.ts';
import {parseDetailedDraft} from '../../packages/detailed-model/schema.ts';
import {detailedReadiness} from '../../packages/detailed-model/readiness.ts';
import {engineeringTopology} from '../../packages/engineering/index.ts';
import {exportDetailedJSON,exportDetailedCSV,importDetailedProfile} from '../../packages/detailed-profile/index.ts';
import {collectDetails,detailSections,getAt,pathText,setAt,type DetailLeaf,type JsonPath,type Scalar} from './detailed-fields';
type Props={project:Project;setProject:(project:Project)=>void};
const PAGE=80;
const errorText=(e:unknown)=>e instanceof Error?e.message:String(e);
function save(content:string,format:'json'|'csv'){const url=URL.createObjectURL(new Blob([content],{type:format==='json'?'application/json':'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`HighwaySwapSim-detailed-settings.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ScalarField({leaf,onChange}:{leaf:DetailLeaf;onChange:(value:Scalar)=>void}){
 const label=`${leaf.label} · detailed.${leaf.key}`;
 if(leaf.readonly)return <code>{String(leaf.value)}</code>;
 if(leaf.type==='boolean')return <label className="switch-label"><Switch aria-label={label} checked={leaf.value===true} onCheckedChange={onChange}/>{leaf.value?'啟用／是':'停用／否'}</label>;
 if(leaf.type==='enum')return <select aria-label={label} className="h-9 w-full rounded-md border bg-transparent px-2 text-sm" value={leaf.value===null?'__null__':String(leaf.value)} onChange={e=>onChange(e.target.value==='__null__'?null:e.target.value)}><option value="__null__">待填（null）</option>{leaf.options?.map(([value,title])=><option key={value} value={value}>{title}</option>)}</select>;
 return <div className="flex gap-2"><Input aria-label={label} type={leaf.type==='number'?'number':'text'} step={leaf.type==='number'?'any':undefined} value={leaf.value===null?'':String(leaf.value)} placeholder={leaf.value===null?'待填（null）':'輸入數值或文字'} onChange={e=>{const raw=e.target.value;if(leaf.type==='number'){const next=raw===''?null:Number(raw);if(next===null||Number.isFinite(next))onChange(next);}else onChange(raw);}}/>{leaf.value!==null&&<Button variant="ghost" size="sm" aria-label={`清除 ${label} 為待填`} onClick={()=>onChange(null)}>待填</Button>}</div>;
}
/** All collection edits are local text until full-config schema validation succeeds. */
function StructureEditor({value,path,onApply,onAppend,onReloadLabel='重新載入目前值'}:{value:unknown;path:JsonPath;onApply:(value:unknown)=>void;onAppend?:(value:unknown)=>unknown;onReloadLabel?:string}){
 const serialized=JSON.stringify(value,null,2),[base,setBase]=useState(serialized),[text,setText]=useState(serialized),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(serialized!==base&&text===base){setBase(serialized);setText(serialized);}},[serialized,base,text]);
 const stale=serialized!==base&&text!==base;
 function apply(candidateText=text){try{if(stale)throw Error('這份結構已被其他欄位更新；請重新載入目前值後再編輯。');const parsed=JSON.parse(candidateText);onApply(parsed);const json=JSON.stringify(parsed,null,2);setBase(json);setText(json);setError('');setMessage('結構已通過完整草稿檢核；請再套用本頁設定。');}catch(e){setError(errorText(e));setMessage('');}}
 function append(){try{if(stale)throw Error('這份結構已被其他欄位更新，請先重新載入目前值。');if(!onAppend)return;const value=onAppend(JSON.parse(text)),json=JSON.stringify(value,null,2);setBase(json);setText(json);setError('');setMessage('已新增待填項目並更新參數表。請填資料，再套用本頁設定。');}catch(e){setError(errorText(e));setMessage('');}}
 function alter(action:'clone'|'delete') {try{const parsed=JSON.parse(text);if(!Array.isArray(parsed)||!parsed.length)throw Error('此操作需要至少一個陣列項目；空陣列請直接貼入符合格式的新項目。');const next=action==='clone'?[...parsed,structuredClone(parsed.at(-1))]:parsed.slice(0,-1);setText(JSON.stringify(next,null,2));setMessage(action==='clone'?'已複製最後一項。請修改新項目的識別碼，再檢核套用。':'已從結構編輯草稿移除最後一項，請檢核套用。');setError('');}catch(e){setError(errorText(e));}}
 return <div className="space-y-3"><p className="tiny mono break-all">detailed{path.length?'.'+pathText(path):''}</p><textarea className="w-full min-h-64 rounded-md border bg-transparent p-3 font-mono text-xs" aria-label={`JSON 結構 ${pathText(path)||'完整模型'}`} value={text} spellCheck={false} onChange={e=>{setText(e.target.value);setError('');setMessage('');}}/><div className="flex flex-wrap gap-2">{onAppend&&<Button disabled={stale} onClick={append}>新增待填項目</Button>}<Button variant="outline" disabled={stale} onClick={()=>apply()}>檢核並更新這份結構</Button>{Array.isArray(value)&&<><Button variant="ghost" onClick={()=>alter('clone')}>複製最後一項新增</Button><Button variant="ghost" onClick={()=>alter('delete')}>刪除最後一項</Button></>}<Button variant="ghost" onClick={()=>{setBase(serialized);setText(serialized);setError('');setMessage('');}}>{onReloadLabel}</Button></div><p className="tiny muted">可在 JSON 中新增、刪除、排序任意項目。識別碼不得重複；未知數值填 null。結構編輯不會即時覆蓋參數表，須先按檢核更新。若要保留尚未套用的文字，請先複製備份再切換集合或離開頁面。</p>{stale&&<p className="notice error" role="alert">目前參數已變更，請重新載入目前值再修改這份結構。</p>}{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}</div>;
}
export function DetailedSettingsPanel({project,setProject}:Props){
 const [draft,setDraft]=useState<DetailedConfig>(()=>project.detailed??defaultDetailedConfig(project)),[section,setSection]=useState('topology'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[collection,setCollection]=useState('');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[reading,setReading]=useState(false),file=useRef<HTMLInputElement>(null),sequence=useRef(0),latest=useRef(project);latest.current=project;
 useEffect(()=>{setDraft(project.detailed??defaultDetailedConfig(project));setError('');},[project.detailed]);
 useEffect(()=>()=>{sequence.current++;},[]);
 const changed=JSON.stringify(draft)!==JSON.stringify(project.detailed??null),details=useMemo(()=>collectDetails(draft,section),[draft,section]);
 const q=query.trim().toLowerCase(),filtered=details.leaves.filter(row=>!q||`${row.context} ${row.label} ${row.key} ${row.value??'待填'}`.toLowerCase().includes(q)),pages=Math.max(1,Math.ceil(filtered.length/PAGE)),effectivePage=Math.min(page,pages-1),shown=filtered.slice(effectivePage*PAGE,(effectivePage+1)*PAGE);
 const arrays=details.arrays.filter(row=>!q||`${row.label} ${pathText(row.path)}`.toLowerCase().includes(q)),selected=arrays.find(row=>pathText(row.path)===collection)??arrays[0];
 const validation=useMemo(()=>{try{parseDetailedDraft(draft);return '';}catch(e){return errorText(e);}},[draft]);
 const issues=useMemo(()=>validation?[]:detailedReadiness({...project,detailed:draft}),[project,draft,validation]);
 function attempt(action:()=>void){try{action();setError('');}catch(e){setError(errorText(e));setMessage('');}}
 function update(path:JsonPath,value:unknown){setDraft(current=>setAt(current,path,value));setError('');setMessage('');}
 function updateStructure(path:JsonPath,value:unknown){const next=parseDetailedDraft(setAt(draft,path,value));setDraft(next);setError('');setMessage('');}
 function appendStructure(path:JsonPath,value:unknown){const candidate=parseDetailedDraft(setAt(draft,path,value)),added=appendDetailedTemplate(latest.current,candidate,path);setDraft(added.config);setQuery(added.focusPath);setPage(0);setError('');setMessage(added.message+' 新項目已在參數表定位；按套用設定前不改變專案。');return getAt(added.config,path);}
 function prepareSlots(){attempt(()=>{const prepared=prepareBatterySlotParameters(latest.current,parseDetailedDraft(draft));setDraft(prepared.config);setSection('service');setQuery('');setPage(0);setCollection(prepared.focusPath);setMessage(prepared.message+' 目前僅更新本頁草稿，按「套用設定」後再重新測算。');});}
 function apply(rebuild=false){attempt(()=>{const detailed=parseDetailedDraft(draft),next={...latest.current,detailed};const applied=rebuild?{...next,topology:engineeringTopology(next)}:next;applied.detailed=syncCostInventory(detailed,applied.topology.nodes);setProject(applied);setDraft(applied.detailed);setMessage(rebuild?'已套用設定並重建完整設備連接。請檢查供電設計，再執行測算。':'已套用完整模型參數，保留目前設備連接。請重新執行測算。');});}
 function download(format:'json'|'csv'){attempt(()=>{const next={...latest.current,detailed:parseDetailedDraft(draft)};save(format==='json'?exportDetailedJSON(next):exportDetailedCSV(next),format);setMessage('已匯出本頁完整參數草稿。這是設定檔，測算結果請另匯出結果 XLSX。');});}
 async function read(f:File){const ticket=++sequence.current;setReading(true);setError('');setMessage('');try{const format=f.name.split('.').pop()?.toLowerCase();if(format!=='json'&&format!=='csv')throw Error('請選完整模型 JSON 或 CSV 設定檔。');if(f.size>8*1024*1024)throw Error('完整模型設定檔上限為 8 MiB。');const content=await f.text();if(sequence.current!==ticket)return;const next=importDetailedProfile(latest.current,content,format);if(!next.detailed)throw Error('匯入檔沒有完整模型設定。');setProject(next);setDraft(next.detailed);setMessage('已匯入並套用完整模型設定。新增設備請明確重建連接；之後重新測算。');}catch(e){if(sequence.current===ticket)setError(errorText(e));}finally{if(sequence.current===ticket)setReading(false);}}
 return <div className="space-y-4"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">DETAILED MODEL SETTINGS</p><h2>完整模型設定</h2></div><span className="pill">{project.detailed?(changed?'有未套用變更':'已套用完整模型'):'完整模型尚未套用'}</span></div><p className="panel-note">逐項填寫設備物理、儲能、乘用車、逐車需求與成本。未知值保留「待填」，啟用相應模型後，必要缺值會列入下方清單。比例欄沿用 0–1，例如 98% 填 0.98；金額沿用本專案 CNY。</p><div className="flex flex-wrap gap-3"><Button disabled={!!validation} onClick={()=>apply()}>套用設定</Button><Button variant="outline" disabled={!!validation||!project.engineering} onClick={()=>apply(true)}>套用並重建設備連接</Button><Button variant="outline" disabled={!!validation} onClick={prepareSlots}>準備逐艙 SOC／回充參數</Button><Button variant="ghost" onClick={()=>{setDraft(project.detailed??defaultDetailedConfig(project));setMessage('已重新載入目前已套用的設定。');setError('');}}>重載已套用設定</Button></div><p className="tiny muted mt-3">先套用參數，再按需要重建設備連接；重建會取代供電設計的手動連線及單台額定覆寫。修改曲線、負載或成本可直接套用；儲能、MPPT、乘用車充電器的效率須與設備轉換參數一致，系統會檢查並提示重建。完整模型的負載設定取代工程頁的負載率。結果圖面與結果 XLSX 使用最後成功測算快照，設定變更後須重新執行。</p><div className="flex flex-wrap gap-3 mt-4"><input ref={file} type="file" accept=".json,.csv" hidden aria-label="選擇完整模型設定檔" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void read(f);}}/><Button variant="outline" disabled={reading} onClick={()=>file.current?.click()}>{reading?'讀取設定中…':'匯入完整模型 JSON／CSV'}</Button><Button variant="outline" disabled={!!validation} onClick={()=>download('json')}>匯出本頁草稿 JSON</Button><Button variant="outline" disabled={!!validation} onClick={()=>download('csv')}>匯出本頁草稿 CSV</Button></div>{validation&&<p className="notice error whitespace-pre-wrap" role="alert">草稿格式待修正：{validation}</p>}{error&&<p className="notice error whitespace-pre-wrap" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}</section>
 <section className="panel"><div className="panel-heading"><h3>物理測算必要資料</h3><span className="pill">{validation?'先修正格式':`${issues.length} 項待處理`}</span></div>{!validation&&issues.length===0?<p className="notice success">目前啟用物理模組的必要欄位檢查通過。請執行測算，再比對逐節點能量帳與測試案例。</p>:<details open><summary>檢視缺項或設備連接問題</summary><ul className="space-y-2 mt-3">{issues.map((issue,i)=><li key={`${issue.path}-${i}`}><code className="text-xs break-all">{issue.path}</code><span className="ml-2">{issue.message}</span></li>)}</ul></details>}<p className="tiny muted">這份清單檢查目前草稿。物理模型資料與財務假設須各自完整；欄位檢核通過不代表實測驗證已完成。</p></section>
 <section className="panel"><div className="form-grid"><Choice label="設定分區" value={section} options={detailSections} onChange={value=>{setSection(value);setPage(0);setCollection('');}}/><label className="field"><span>搜尋名稱、完整路徑或數值</span><Input aria-label="搜尋完整模型參數" value={query} placeholder="例如 A-pcs、chargeEfficiency、初始 SOC" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div><p className="tiny muted mt-3">找到 {filtered.length} 個參數，顯示第 {effectivePage*PAGE+(shown.length?1:0)}–{effectivePage*PAGE+shown.length} 個。所有編輯先留在本頁草稿，按「套用設定」才更新專案。</p><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>參數</TableHead><TableHead>完整路徑</TableHead><TableHead className="min-w-64">目前草稿值</TableHead></TableRow></TableHeader><TableBody>{shown.map(leaf=><TableRow key={leaf.key}><TableCell><strong>{leaf.label}</strong>{leaf.context&&<p className="tiny muted break-all">{leaf.context}</p>}{leaf.unit&&<p className="tiny muted">{leaf.unit}</p>}</TableCell><TableCell><code className="text-xs break-all">detailed.{leaf.key}</code></TableCell><TableCell><ScalarField leaf={leaf} onChange={value=>update(leaf.path,value)}/></TableCell></TableRow>)}</TableBody></Table></div>{filtered.length===0&&<p className="empty-state">目前分區沒有符合搜尋的欄位。</p>}<div className="flex items-center gap-3 mt-3"><Button variant="outline" disabled={effectivePage===0} onClick={()=>setPage(effectivePage-1)}>上一頁</Button><span>{effectivePage+1} / {pages}</span><Button variant="outline" disabled={effectivePage+1>=pages} onClick={()=>setPage(effectivePage+1)}>下一頁</Button></div></section>
 <section className="panel"><h3>電池艙 SOC 與回充設定</h3><p className="panel-note">按「準備逐艙 SOC／回充參數」，可在車輛服務分區逐艙編輯初始 SOC、容量、SOH、回充功率與電池充入儲存效率。圖面的 SOC 為測算結果，隨時間軸更新；修改初始條件後須套用並重跑。</p><p className="tiny muted">站內回充 SOC 分段限功率（chargeBands）限制電池端輸入功率；每段須填電壓、功率及電流上限，連續覆蓋 SOC 0–1。SOC 與儲能比例對照（energySOC）以容量 × SOH 為儲能基準。曲線 null 分別表示固定功率及線性對照假設，並非已驗證的 BMS 曲線；可在下方集合選擇对应電池艙後新增待填曲線，或以 JSON／CSV 整體匯入匯出。</p></section>
 <section className="panel"><h3>集合、曲線與事件結構</h3><p className="panel-note">新增／刪除設備模型、曲線點、到站事件、資產或時序，可按「新增待填項目」產生可編輯欄位，或修改完整 JSON。模板保留未知值，未確認的規格與費率不會代填。</p>{arrays.length>0&&selected?<><Choice label="選擇要修改的集合" value={pathText(selected.path)} onChange={setCollection} options={arrays.map(row=>[pathText(row.path),`${row.label} · ${pathText(row.path)} · ${row.count===null?'待填':`${row.count} 項`}`])}/><StructureEditor key={pathText(selected.path)} path={selected.path} value={getAt(draft,selected.path)} onApply={value=>updateStructure(selected.path,value)} onAppend={hasDetailedTemplate(selected.path)?value=>appendStructure(selected.path,value):undefined}/></>:<p className="tiny muted">此分區或搜尋條件沒有集合欄位。完整設定結構仍可於下方編輯。</p>}</section>
 <section className="panel"><details><summary>進階：完整設定 JSON 編輯器</summary><p className="panel-note mt-3">包含所有分區；適用新增空集合的第一個項目或一次修改相關欄位。只能輸入完整模型設定物件，設定交換檔請用上方匯入。</p><StructureEditor path={[]} value={draft} onApply={value=>updateStructure([],value)}/></details></section></div>;
}
