"use client";
import {useMemo} from 'react';
import {fmt} from './controls';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '../ui/table';
import type {RunResult} from '../../packages/contracts/index.ts';
import type {FlowView} from '../../packages/power-trace/index.ts';
import {flowBoundary} from '../../packages/flow-boundary/index.ts';
export function DetailedFlowSummary({result,view}:{result:RunResult;view:FlowView}){
 const boundary=useMemo(()=>flowBoundary(result,view),[result,view]),power=view.mode==='power',display=(n:number|null)=>boundary.available&&n!==null?fmt(n,4):'—';
 const rows:[string,number|null][]=[['電網購入',boundary.grid],['光伏實際採收（MPPT 前）',boundary.pv],['外部總輸入',boundary.externalInput],['服務與站用末端（含換電補電）',boundary.serviceTerminal],['對外售電',boundary.export],['網路設備轉換及線損',boundary.networkLoss],['儲能自放電',boundary.selfDischarge],['儲能被動損耗合計',boundary.passiveLoss],['全站總損耗',boundary.totalLoss],[power?'儲能變化率 dE/dt':'儲能庫存變化 ΔE',boundary.storageDelta],['全站邊界殘差',boundary.externalResidual]];
 return <section aria-label="完整模型能量邊界" className="space-y-4">{boundary.issues.map((issue,i)=><p className="notice error" role="alert" key={i}>{issue}</p>)}<div className="flow-summary">{rows.map(([label,value])=><div key={label}><span>{label}</span><strong>{label==='全站邊界殘差'&&value!==null?boundary.available?value.toExponential(3):'—':display(value)} <small>{view.unit}</small></strong></div>)}<p>外部輸入＝電網購入＋光伏實際採收。ESS／UPS 的放電與回充屬站內移轉，圖上的儲能來源不能再次加成外部發電。服務末端包含換電電池補電；實際換電交付另列營運帳。</p></div>
 <details className="panel"><summary>查看同一時間窗的能量邊界公式與站內移轉</summary><p className="mono text-sm break-all">{display(boundary.externalInput)} − {display(boundary.export)} − {display(boundary.serviceTerminal)} − {display(boundary.networkLoss)} − {display(boundary.passiveLoss)} − {display(boundary.storageDelta)} = {boundary.externalResidual===null?'未計算':boundary.externalResidual.toExponential(4)} {view.unit}</p><p className="tiny muted">外部輸入 − 對外售電 − 服務及站用末端 − 網路損耗 − 儲能被動損耗 − 儲能庫存變化。儲能充／放電轉換損耗已包含在圖面設備損耗，不重複扣除。</p><div className="flow-summary">{([['站內儲能來源端放電',boundary.storageWithdrawal],['站內儲能入庫端回充',boundary.storageCharge],['光伏可採收上限',boundary.pvAvailable],['未採收光伏（棄光）',boundary.pvCurtailed],['圖面連接守恆殘差',boundary.networkResidual]] as [string,number][]).map(([label,value])=><div key={label}><span>{label}</span><strong>{display(value)} <small>{view.unit}</small></strong></div>)}</div><p className="tiny muted">棄光是尚未採收的可用能源，不是已購入能源的損耗。圖面連接帳會包含所有電源端口；全站外部帳會消除儲能內部移轉。</p></details>
 {boundary.storage.length>0&&<details className="panel"><summary>逐台儲能庫存與損耗</summary><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>儲能</TableHead><TableHead>{power?'目前庫存 kWh':'期初庫存 kWh'}</TableHead>{!power&&<TableHead>期末庫存 kWh</TableHead>}<TableHead>充電輸入 {view.unit}</TableHead><TableHead>放電輸出 {view.unit}</TableHead><TableHead>轉換損耗 {view.unit}</TableHead><TableHead>自放電 {view.unit}</TableHead><TableHead>{power?'此刻離散容量損失 kWh':'容量衰減溢出損失 kWh'}</TableHead><TableHead>{power?'庫存變化 kW':'庫存變化 kWh'}</TableHead><TableHead>守恆殘差 {view.unit}</TableHead></TableRow></TableHeader><TableBody>{boundary.storage.map(row=><TableRow key={row.id}><TableCell>{row.station} 區 · {row.kind}<br/><code>{row.id}</code></TableCell><TableCell>{display(row.initialStoredKWh)}</TableCell>{!power&&<TableCell>{display(row.finalStoredKWh)}</TableCell>}<TableCell>{display(row.input)}</TableCell><TableCell>{display(row.output)}</TableCell><TableCell>{display(row.conversionLoss)}</TableCell><TableCell>{display(row.selfDischarge)}</TableCell><TableCell>{display(row.capacitySpillKWh)}</TableCell><TableCell>{display(row.delta)}</TableCell><TableCell>{row.balanceResidual.toExponential(3)}</TableCell></TableRow>)}</TableBody></Table></div><p className="tiny muted">自放電按已保存的庫存、效率及自放電率求連續時間解，任意子分鐘區间不按整段平均損耗攤分。容量衰減溢出是離散期末調整，保留 kWh；不把它除以步長冒充當下 kW。{boundary.storageEndpointPolicy}</p></details>}
 {power?<p className="flow-footnote">當下模式呈現連續功率與儲能變化率。換電交付及離散容量調整屬事件能量；切換每小時或區間累計查看營運與庫存帳。</p>:boundary.operating&&<details className="panel"><summary>另核對營運交付與換電庫存</summary>{boundary.operating.available?<><div className="flow-summary">{([['換電淨交付',boundary.operating.swapDeliveredKWh],['直充槍端交付',boundary.operating.directDeliveredKWh],['換電電池庫存變化',boundary.operating.swapBatteryDeltaKWh],['站用電量',boundary.operating.auxiliaryKWh],['營運全站能量殘差',boundary.operating.balanceResidualKWh]] as [string,number][]).map(([label,value])=><div key={label}><span>{label}</span><strong>{label.includes('殘差')?value.toExponential(3):display(value)} <small>kWh</small></strong></div>)}</div><p className="tiny muted">這裡以「換電淨交付＋換電庫存變化」取代上方的換電庫存補電，兩種帳不能再次相加。直充採槍端交付口徑，車內儲存與損失另見服務帳。{boundary.operating.swapEndpointPolicy}</p></>:<p className="notice">{boundary.operating.reason??'缺少可驗算的庫存資料，請重新測算。'}</p>}</details>}
 </section>;
}
