"use client";
import { useState } from 'react';
import { BatteryCharging, BatteryFull, Car, Truck, Fuel, Zap, Server, Cable, Gauge, ArrowDown, CircuitBoard } from 'lucide-react';
import { Button } from '../ui/button';
import { Switch } from '../ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table';
import { Choice, NumberField, Stat, fmt } from './controls';
import type { Project, EngineeringConfig } from '../../packages/contracts/index.ts';
import { capacityCase, CATL_SOURCE, engineeringTopology, physicalProjection, truckPacks } from '../../packages/engineering/index.ts';

export function EquipmentGlyph({type,size=24}:{type:string;size?:number}){const Icon=type==='passenger'?Car:type==='swap-bay'?Truck:type==='rack'?BatteryFull:type==='gun'?Fuel:type==='charger'?BatteryCharging:type==='meter'?Gauge:type.includes('cable')?Cable:type==='sst'||type==='pcs'?Server:type==='grid'?Zap:CircuitBoard;return <Icon size={size} strokeWidth={1.6}/>;}
export function FacilityMap({project,onDesign}:{project:Project;onDesign?:()=>void}){
 const [selected,setSelected]=useState<string|null>(null);const c=project.engineering;if(!c)return <p>此情境為原始簡化模型，請載入完整設備案例。</p>;
 const node=project.topology.nodes.find(n=>n.id===selected);
 const equipment=(id:string,type:string,title:string,detail:string)=>{const n=project.topology.nodes.find(n=>n.id===id);return <button className={`equipment-tile ${!n?.enabled?'equipment-off':''} ${selected===id?'equipment-selected':''}`} onClick={()=>setSelected(id)} aria-pressed={selected===id}><EquipmentGlyph type={type}/><span><strong>{title}</strong><small>{detail}</small></span><i className={n?.enabled?'status-dot':'off-dot'}/></button>;};
 return <><div className="facility-legend"><span className="ac-key">交流 10 kV / 400 V</span><span className="dc-key">直流 800 V</span><span>點選設備查看規格 · 配置示意，非即時功率</span></div><div className="facility-grid">{(['A','B'] as const).map(s=>{const st=project.station[s];return <article className="facility-site" key={s}><div className="facility-site-title"><span>{s}</span><div><h3>服務區 {s}</h3><small>{s==='A'?'主接入 · 向兩區 SST 供電':'獨立箱變接入 · SST 由 A 區供電'}</small></div><b>{fmt(project.topology.nodes.find(n=>n.id===`${s}-grid`)?.params.kva??0)} kVA</b></div>
 <div className="facility-zone ac-zone"><p className="zone-label">01 / 供電與配電</p><div className="equipment-row">{equipment(`${s}-grid`,'grid','電網接入','10 kV')}{equipment(`${s}-incoming`,'mv-switch','進線櫃','中壓配電')}{equipment(`${s}-meter`,'meter','計量櫃','來源電量計量')}</div><div className="feed-caption"><ArrowDown size={14}/> 出線櫃 → 負荷開關 → SST / 箱變</div><div className="equipment-row">{[0,1].map(i=><div key={i}>{equipment(`${s}-sst-${i}`,'sst',`SST ${i+1}`,i<project.phase?'1680 kW · DC 800 V':'二期預留工位')}</div>)}{equipment(`${s}-transformer`,'transformer','箱式變壓器','2500 kVA · 10 / 0.4 kV')}</div><div className="equipment-row">{equipment(`${s}-lv`,'lv-bus','低壓饋線櫃','AC 400 V')}{equipment(`${s}-pcs`,'pcs','PCS 整流櫃',`${fmt(project.topology.nodes.find(n=>n.id===`${s}-pcs`)?.params.kw??0)} kW`)}{equipment(`${s}-compensation`,'compensation','功率補償櫃','kvar 待確認')}</div></div>
 <div className="bus-strips"><button onClick={()=>setSelected(`${s}-bus-sst`)}>母線 1 · SST · DC 800 V</button><button onClick={()=>setSelected(`${s}-bus-pcs`)}>母線 2 · PCS · DC 800 V</button></div>
 <div className="facility-zone truck-zone"><p className="zone-label">02 / 重卡換電站</p>{equipment(`${s}-swap-bay`,'swap-bay','重卡換電工位',`${st.bays} 工位 · ${fmt(st.swapMinutes,1)} min / 次 · ${st.auxiliaryKW} kW 站用上限`)}<div className="battery-racks">{Array.from({length:st.batteries},(_,i)=>{const n=project.topology.nodes.find(n=>n.id===`${s}-rack-${i}`);return <button key={i} onClick={()=>setSelected(`${s}-rack-${i}`)} className={!n?.enabled?'equipment-off':''}><BatteryFull size={29}/><strong>倉 {i+1}</strong><small>{fmt(st.capacityKWh,2)} kWh</small><span>{i>=st.batteries-c.pcsSlotsPerSite?'PCS':'SST'} · DD {fmt(st.batteryChargeKW)} kW</span></button>;})}</div><p className="tiny muted">SOC {st.returnSOC*100}% → {st.readySOC*100}% · 電池倉與換電工位分別計數。電池圖示不表示即時 SOC。</p></div>
 <div className="facility-zone charging-zone"><p className="zone-label">03 / 共享超充</p>{equipment(`${s}-stack`,'charger','DD 超充堆',`${fmt(st.chargePoolKW)} kW 共享功率池`)}<div className="terminal-grid">{Array.from({length:Math.ceil(st.guns/2)},(_,i)=><div className="terminal" key={i}><button className="terminal-label" onClick={()=>setSelected(`${s}-terminal-${i}`)}>液冷雙槍終端 {i+1}</button><div>{[i*2,i*2+1].filter(g=>g<st.guns).map(g=><button key={g} onClick={()=>setSelected(`${s}-gun-${g}`)} className={!project.topology.nodes.find(n=>n.id===`${s}-gun-${g}`)?.enabled?'equipment-off':''}><Fuel size={31}/><strong>槍 {g+1}</strong><small>≤ {st.gunKW} kW</small><small>600 A / 1000 V</small></button>)}</div></div>)}</div><p className="tiny muted">4 槍共用 1440 kW；車端電壓及上游剩餘容量會再限制可交付功率。</p></div>
 <div className="facility-zone passenger-zone"><p className="zone-label">04 / 乘用車換電</p>{equipment(`${s}-passenger`,'passenger','CATL 巧克力換電站',`${c.passengerSlots} 倉 · ${c.passengerSwapSeconds} 秒 / 次`)}<div className="choco-racks" aria-label={`${c.passengerSlots}個巧克力電池倉`}>{Array.from({length:c.passengerSlots},(_,i)=><span key={i}>{i+1}</span>)}</div><p className="tiny">AC 充電 {c.passengerChargerKW} + 站用 {c.passengerAuxKW} kW（附件配置）。目前按共用負載計算。</p></div>
 </article>;})}</div><div className="intertie-banner"><Cable size={23}/><div><strong>雙區直流母聯 · 150 m</strong><p>{c.intertie?'已啟用跨站饋線，SST / PCS 兩條母線分開共享。':'已斷開跨站饋線，兩區各用自身的直流來源。'}10 kV 跨站供電來自 Grid A；Grid B 不與 Grid A 的 AC 母線並聯。</p></div></div>
 {node&&<div className="equipment-detail" role="status"><EquipmentGlyph type={node.type}/><div><strong>{node.station} 區 · {node.name}</strong><p>{node.id} · {node.enabled?'已啟用':'停用 / 預留'}</p></div><dl>{Object.entries(node.params).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{fmt(v,2)}</dd></div>)}</dl>{onDesign&&<Button variant="outline" onClick={onDesign}>開啟設備編輯 ↗</Button>}</div>}</>;
}

export function EngineeringPanel({project,setProject}:{project:Project;setProject:(p:Project)=>void}){
 const c=project.engineering;if(!c)return <section className="panel"><p>請在上方載入「完整設備案例」。</p></section>;const v=capacityCase(project);
 const update=(patch:Partial<EngineeringConfig>)=>{const p={...project,engineering:{...c,...patch}};setProject({...p,topology:engineeringTopology(p)});};
 return <><section className="panel"><div className="panel-heading"><div><p className="eyebrow">EQUIPMENT & CAPACITY / 513 kWh</p><h2>從接入容量，算到每支槍。</h2></div><Button onClick={()=>setProject(physicalProjection(project))}>載入 410.4 kWh 物理案例</Button></div><p className="panel-note">原始八月表使用 410 kWh / 次，保持原值；物理案例以目前電池容量和 SOC 窗口重算換電需求，仍保留原車次與直接充電資料。載入後請執行測算。</p><div className="stats-grid"><Stat label="每次補電" value={fmt(v.energy,2)} unit="kWh"/><Stat label="8 次 / h 的 DD 輸入" value={fmt(v.hourlyDD,2)} unit="kW"/><Stat label="兩台 SST 輸出" value="3,360" unit="kW" note="兩台合計；不是每側一期容量"/><Stat label="連續補電缺口" value={fmt(v.sstDeficit,2)} unit="kW" note={`能量上限 ${fmt(v.sustainableSST,4)} 次 / h`}/></div><p className="notice">3360 kW 略低於精確需求 3370.84 kW（附件原列 3370.76 kW）。初始滿電庫存可暫時支援 8 次 / h，但不代表持續補電已達平衡。</p></section>
 <div className="two-column"><section className="panel"><h2>箱變 → 交流負載 → PCS</h2><p className="panel-note">容量設計以交流負載滿載核算；下面為 A 側目前設定，第 {project.phase} 期。二期每側 2 台 SST 時可重現附件的 770 / 1622.39 kW。</p><div className="capacity-flow"><p>2500 kVA × PF 0.99 × 箱變效率<strong>{fmt(v.transformerOutput,2)} kW</strong></p><p>乘用車 + 重卡站用 + SST 運行<strong>− {fmt(v.ac,2)} kW</strong></p><p>PCS 可用交流輸入<strong>{fmt(v.pcsInput,2)} kW</strong></p><p>PCS 直流輸出（另受額定限制）<strong>{fmt(v.pcsOutput,2)} kW</strong></p></div><Table><TableHeader><TableRow>{['PCS 補電倉','DD 輸入 kW','剩餘 DC kW','按同動率配置 kW'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{v.residuals.map(x=><TableRow key={x.slots}><TableCell>{x.slots}</TableCell><TableCell>{fmt(x.ddInput,2)}</TableCell><TableCell>{fmt(x.residual,2)}</TableCell><TableCell>{fmt(x.configured,2)}</TableCell></TableRow>)}</TableBody></Table><p className="tiny muted">每倉列值代表一小時補回 {fmt(v.energy,2)} kWh 的平均輸入；不是 560 kW 額定。除以同動率僅估裝機容量，不放大可供電功率。</p></section>
 <section className="panel"><h2>雙區 2880 kW 超充檢核</h2><p className="panel-note">A 側配置對稱推算，PCS 每側 {c.pcsSlotsPerSite} 倉平均補電；已扣一次 DD 效率。手動改為不對稱拓撲時，請以受限模擬結果為準。</p><Table><TableHeader><TableRow>{['同動率','槍端需求 kW','可交付上限 kW','缺口 kW'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{v.concurrency.map(x=><TableRow key={x.factor}><TableCell>{fmt(x.factor*100)}%</TableCell><TableCell>{fmt(x.request,2)}</TableCell><TableCell>{fmt(x.available,2)}</TableCell><TableCell className={x.deficit?'text-amber-700':''}>{fmt(x.deficit,2)}</TableCell></TableRow>)}</TableBody></Table><p className="notice">雙區可用功率的「範圍」不代表所有工況均可滿足需求。來源最低母線功率 1559.36 kW，小於 60% 同動需求 1728 kW。</p><div className="stats-grid compact two"><Stat label="車端電壓" value={fmt(c.packVoltage,2)} unit="V"/><Stat label="600 A 下單槍上限" value={fmt(v.gunLimit,2)} unit="kW"/></div><p className="tiny">480 kW 需要 800 V × 600 A；637.56 V 時最多 382.536 kW。4 終端 / 8 槍共用 2880 kW，可配置 6×480 或 4×480+4×240；8×480 需求會受功率池限制。</p></section></div>
 <section className="panel"><h2>雙站充電倉配置對照</h2><p className="panel-note">來源表的 SST 欄固定 8 次 / h，按雙站一期共 2 台 SST 解讀。總共 16 倉；不是每側 16 倉。右欄用目前期別重算供能上限，尚受實際機械、排隊與共享負載約束。</p><Table><TableHeader><TableRow>{['SST 倉','PCS 倉','來源 SST 次/h','來源 PCS 次/h','來源合計','目前期別供能上限'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{v.allocationRows.map(x=><TableRow key={x.pcsSlots}><TableCell>{x.sstSlots}</TableCell><TableCell>{x.pcsSlots}</TableCell><TableCell>{x.sourceSST}</TableCell><TableCell>{x.sourcePCS}</TableCell><TableCell>{x.sourceTotal}</TableCell><TableCell>{fmt(x.energyUpper,3)}</TableCell></TableRow>)}</TableBody></Table></section>
 <div className="two-column"><section className="panel"><h2>案例配置與負載假設</h2><p className="panel-note">這些控制會同步重建詳細拓撲，取代手動連線編輯。容量表用滿載；連續期間模擬使用下列可調負載係數。</p><Choice label="每側由 PCS 補電的倉數" value={String(c.pcsSlotsPerSite)} onChange={v=>update({pcsSlotsPerSite:Number(v)})} options={[["0","0 · 兩側 16 SST / 0 PCS"],["1","1 · 兩側 14 SST / 2 PCS"],["2","2 · 兩側 12 SST / 4 PCS"],["3","3 · 兩側 10 SST / 6 PCS"]]}/><label className="switch-label"><Switch checked={c.intertie} onCheckedChange={intertie=>update({intertie})}/>跨站直流互濟</label><div className="form-grid"><NumberField label="裝機同動率" min={.1} max={1} value={c.simultaneity} onChange={v=>update({simultaneity:v??.6})}/><NumberField label="車端電壓" unit="V" min={1} max={1000} value={c.packVoltage} onChange={v=>update({packVoltage:v??637.56})}/><NumberField label="乘用車負載係數" min={0} max={1} value={c.passengerLoadFactor} onChange={v=>update({passengerLoadFactor:v??0})}/><NumberField label="重卡站用負載係數" min={0} max={1} value={c.truckAuxLoadFactor} onChange={v=>update({truckAuxLoadFactor:v??0})}/></div></section>
 <section className="panel"><h2>CATL 巧克力換電站</h2><p>採用 #20 / #25 巧克力站公開資料：14–30 倉、99 秒換電、相容軸距 2.55–3.10 m。<a className="source-link" href={CATL_SOURCE} target="_blank" rel="noreferrer">CATL 官方資料 ↗</a></p><p className="tiny muted">查核 2026-09-08。2024 發布稿寫 100 秒，現行產品頁寫 99 秒；不混用 2022 EVOGO 的 48 電塊 / 約 1 分鐘規格。99 秒是單次作業指標，不能直接換算持續日服務量。</p><div className="form-grid"><NumberField label="電池倉數" min={14} max={30} value={c.passengerSlots} onChange={v=>update({passengerSlots:v??14})}/><NumberField label="換電作業時間" unit="秒" value={c.passengerSwapSeconds} onChange={v=>update({passengerSwapSeconds:v??99})}/><NumberField label="AC/DC 充電配置" unit="kW" value={c.passengerChargerKW} onChange={v=>update({passengerChargerKW:v??500})}/><NumberField label="站用配置" unit="kW" value={c.passengerAuxKW} onChange={v=>update({passengerAuxKW:v??50})}/></div><p className="notice">500 + 50 kW 來自附件方案，非 CATL 官方額定。尚無乘用車到站需求；本版以共用交流負載計算，不產生乘用車換電收入。</p></section></div>
 <section className="panel"><h2>重卡電池選型來源表</h2><p className="panel-note">以下為使用者附件轉錄。Ah / 電流含模組或並聯口徑，未確認前不可直接以單組 V×Ah 取代總電量。</p><Table><TableHeader><TableRow>{['總電量 kWh','原列容量 Ah','原列充電電流','額定 V','電壓範圍 V'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{truckPacks.map(x=><TableRow key={x.kWh}><TableCell>{x.kWh}</TableCell><TableCell>{x.ah}</TableCell><TableCell>{x.current}</TableCell><TableCell>{x.voltage}</TableCell><TableCell>{x.minV}–{x.maxV}</TableCell></TableRow>)}</TableBody></Table></section></>;
}
