"use client";
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ChevronLeft, ChevronRight, Focus, Maximize, Pause, Play, Search, ZoomIn, ZoomOut } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Slider } from '../ui/slider';
import { Switch } from '../ui/switch';
import { Choice, fmt } from './controls';
import { EquipmentGlyph } from './facility';
import { flowBoundary } from '../../packages/flow-boundary/index.ts';
import { batteryStateAt } from '../../packages/battery-trace/index.ts';
import { DetailedFlowSummary } from './detailed-flow-summary';
import { flowView, integrateSignal, isFlowSourceType, type FlowMode, type FlowNode, type FlowView } from '../../packages/power-trace/index.ts';
import type { Equipment, Project, RunResult } from '../../packages/contracts/index.ts';
import './flow-explorer.css';
import {referenceLayout,referenceWire} from '../../packages/reference-layout/index.ts';
import {ReferenceBackdrop} from './reference-backdrop';
import './reference-layout.css';

const STATUS:Record<FlowNode['status'],string>={off:'停用 / 預留',interlock:'輔助供電閉鎖',shortfall:'輔助供電不足',mixed:'此區間狀態有變',limited:'供給受限',idle:'零功率',flow:'有能量流',unmodeled:'無功未建模',unknown:'未計算',empty:'空區間'};
type BatteryCursorState=NonNullable<ReturnType<typeof batteryStateAt>>;
const BATTERY_STATUS:Record<BatteryCursorState['status'],string>={charging:'充電中',ready:'達標可換出',swapping:'換電中', 'waiting-power':'等待供電',disabled:'回充停用'};
const isBatteryRack=(device:Equipment)=>device.type==='rack'||device.type==='passenger-rack';
const W=250,H=148,RATIO=1.6;
type Box={x:number;y:number;w:number;h:number};
export function flowTime(minute:number){const milliseconds=Math.round(minute*60000),day=Math.floor(milliseconds/86400000),within=milliseconds%86400000;return `D${day+1} ${String(Math.floor(within/3600000)).padStart(2,'0')}:${String(Math.floor(within/60000)%60).padStart(2,'0')}:${(within%60000/1000).toFixed(3).padStart(6,'0')}`;}
function bounds(nodes:{x:number;y:number}[]):Box{const x=Math.min(...(nodes.length?nodes.map(n=>n.x):[0]))-45,y=Math.min(...(nodes.length?nodes.map(n=>n.y):[0]))-65,w=Math.max(600,...nodes.map(n=>n.x+W))-x+45,h=Math.max(400,...nodes.map(n=>n.y+H))-y+45;return {x,y,w:Math.max(w,h*RATIO),h:Math.max(h,w/RATIO)};}
function precise(n:number){return Number.isFinite(n)?String(Number(n.toPrecision(13))):'—';}
export function batteryFrame(result:RunResult,minute:number){const trace=result.detailedResult?.batteryTrace;const racks=result.parameterSnapshot.topology.nodes.filter(isBatteryRack);const queried=racks.map(n=>({sink:n.id,state:trace?batteryStateAt(trace,n.id,minute):null}));return {atMinute:minute,quantity:'state-at-cursor',available:!!trace,states:queried.flatMap(n=>n.state?[n.state]:[]),missingSinkIds:queried.filter(n=>!n.state).map(n=>n.sink)};}
function downloadFrame(result:RunResult,view:FlowView){const data={batteryState:batteryFrame(result,view.minute),engineVersion:result.engineVersion,parameterSnapshot:result.parameterSnapshot,selection:{minute:view.minute,from:view.from,to:view.to,mode:view.mode,unit:view.unit},nodes:view.nodes,edges:view.edges,conservation:{grid:view.grid,sourceInput:view.sourceInput??view.grid,pvInput:view.pvInput??0,storageInput:view.storageInput??0,upsInput:view.upsInput??0,terminal:view.terminal,loss:view.loss,maxResidual:view.maxResidual},systemBoundary:result.detailedResult?flowBoundary(result,view):{input:view.grid,output:view.terminal,loss:view.loss,unit:view.unit,outputDefinition:'Terminal absorption; intermediate transfers excluded'}};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`HighwaySwapSim-flow-${view.mode}-${view.from}-${view.to}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function FlowExplorer({result,busy=false,onRunCurrent,onRunDemo}:{result:RunResult;busy?:boolean;onRunCurrent?:()=>void;onRunDemo?:()=>void}){
 const [arrangement,setArrangement]=useState('reference');
 const [minute,setMinute]=useState(0),[mode,setMode]=useState<FlowMode>('power'),[rangeStart,setRangeStart]=useState(0),[selected,setSelected]=useState(result.parameterSnapshot.topology.nodes[0]?.id??''),[playing,setPlaying]=useState(false),[labels,setLabels]=useState(false),[query,setQuery]=useState('');
 const project=result.parameterSnapshot,horizon=project.horizonDays*1440;
 const layout=useMemo(()=>arrangement==='reference'?referenceLayout(project.topology):project.topology.nodes.map(n=>({...n,x:n.x*1.45,y:n.y*1.95})),[project,arrangement]);
 const full=useMemo(()=>bounds(layout),[layout]),[camera,setCamera]=useState<Box|null>(null),box=camera??full;
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;box:Box}|null>(null),prefix=useId().replace(/:/g,'');
 const hourMinute=Math.min(Math.floor(minute/60),horizon/60-1)*60;
 const hourView=useMemo(()=>flowView(result,hourMinute,'energy'),[result,hourMinute]);
 const view=useMemo(()=>mode==='energy'?({...hourView,minute}):flowView(result,minute,mode,rangeStart),[result,minute,mode,rangeStart,hourView]);
 const nodeMap=useMemo(()=>new Map(layout.map(n=>[n.id,n])),[layout]),values=new Map(view.nodes.map(n=>[n.id,n]));
 const device=nodeMap.get(selected),node=values.get(selected),hourNode=hourView.nodes.find(n=>n.id===selected);
 const rackStates=useMemo(()=>{const trace=result.detailedResult?.batteryTrace;return new Map(layout.filter(isBatteryRack).map(n=>[n.id,trace?batteryStateAt(trace,n.id,minute):null] as const));},[result,layout,minute]);
 const selectedBattery=rackStates.get(selected)??null;
 const events=useMemo(()=>mode==='energy'?Array.from({length:project.horizonDays*24+1},(_,i)=>i*60):[...new Set([...result.powerTrace?.eventMinutes??[],...(result.detailedResult?.batteryTrace?.slots.flatMap(s=>s.intervals.map(r=>r.fromMinute))??[]),...(result.detailedResult?.storage.filter(r=>(r.capacitySpillKWh??0)>0).map(r=>r.toMinute)??[]),...(result.detailedResult?.serviceEvents.filter(e=>e.kind==='swap-complete'||e.kind==='charge-complete').map(e=>e.atMinute)??[]),horizon])].sort((a,b)=>a-b),[result,mode,horizon,project.horizonDays]);
 useEffect(()=>{setMinute(0);setRangeStart(0);setPlaying(false);setCamera(null);setSelected(result.parameterSnapshot.topology.nodes[0]?.id??'');},[result]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setMinute(current=>{const next=events.find(t=>t>current);if(next===undefined||next>=horizon){setPlaying(false);return horizon;}return next;}),650);return ()=>clearInterval(timer);},[playing,events,horizon]);
 function changeTime(t:number){setPlaying(false);setMinute(Math.max(mode==='cumulative'?rangeStart:0,Math.min(horizon,t)));}
 function jump(direction:number){changeTime(direction>0?events.find(t=>t>minute)??horizon:events.filter(t=>t<minute).at(-1)??0);}
 function zoom(factor:number){setCamera(old=>{const b=old??full,w=Math.max(500,Math.min(full.w*2,b.w*factor));return {x:b.x+(b.w-w)/2,y:b.y+(b.h-w/RATIO)/2,w,h:w/RATIO};});}
 function focus(id:string){const n=nodeMap.get(id);if(!n)return;setSelected(id);setCamera({x:n.x+W/2-550,y:n.y+H/2-550/RATIO,w:1100,h:1100/RATIO});}
 const display=(value:number)=>view.available?fmt(value,2):'—';
 const statusLabel=(n:FlowNode)=>mode==='power'?STATUS[n.status]:n.status==='idle'?'區間零電量':STATUS[n.status];
 const links=view.edges.filter(e=>e.source===selected||e.target===selected),matches=layout.filter(n=>`${n.station} ${n.name} ${n.id}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="flow-explorer" aria-label="能量流驗算">
  <div className="flow-heading"><div><p className="eyebrow">ENERGY FLOW EXPLORER</p><h2>沿著每一條線，核對每一度電。</h2><p>完整連接圖 · {layout.length} 個節點 / {view.edges.length} 條連線 · 結果快照：{project.name}</p></div><div className="flow-actions">{onRunCurrent&&<Button disabled={busy} variant="outline" onClick={onRunCurrent}>執行目前受限參數</Button>}{onRunDemo&&<Button disabled={busy} onClick={onRunDemo}><Play size={16}/>完整設備案例 · 3 天</Button>}</div></div>
  {!view.available&&<div className="flow-unavailable" role="status"><strong>尚無可驗算的功率記錄</strong><p>{result.mode==='SOURCE_REPLAY'?'來源原表重播沒有模擬節點功率。請執行受限參數，或載入右上方的 3 天完整設備案例。':'此結果未保存事件功率記錄，請重新執行測算；仍可切換每小時電量。'}「—」表示未計算，並非零功率。</p></div>}
  <div className="flow-timeline">
   <div className="flow-time-top"><div><span className="eyebrow">{mode==='cumulative'?'區間累計 · kWh':mode==='power'?'事件功率 · 不插值':'整小時積分電量'}</span><strong className={`flow-clock ${mode==='cumulative'?'is-range':''}`} aria-live="polite">{mode==='cumulative'&&`${flowTime(rangeStart)} → `}{flowTime(minute)}{mode!=='cumulative'&&minute===horizon?' · 期末左極限':''}</strong></div><Choice label="圖面數值" value={mode} onChange={value=>{setMode(value as FlowMode);setPlaying(false);if(value==='cumulative'){const end=minute===0?horizon:minute;setRangeStart(Math.min(rangeStart,end));setMinute(end);}}} options={[["power","當下功率 kW"],["energy","每小時電量 kWh"],["cumulative","區間累計 kWh"]]}/><label className="field"><span>{mode==='cumulative'?'累計終點 · 自期初起分鐘':'精確時間 · 自期初起分鐘'}</span><Input type="number" min={mode==='cumulative'?rangeStart:0} max={horizon} step="any" value={minute} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))changeTime(n);}}/></label><div className="flow-play"><Button variant="outline" size="icon" aria-label="上一個變化時刻" disabled={!view.available||minute===(mode==='cumulative'?rangeStart:0)} onClick={()=>jump(-1)}><ChevronLeft size={18}/></Button><Button variant="outline" size="icon" aria-label={playing?'暫停時間軸':'播放時間軸'} disabled={!view.available} onClick={()=>{if(minute>=horizon)setMinute(mode==='cumulative'?rangeStart:0);setPlaying(!playing);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</Button><Button variant="outline" size="icon" aria-label="下一個變化時刻" disabled={!view.available||minute===horizon} onClick={()=>jump(1)}><ChevronRight size={18}/></Button></div></div>
   {mode==='cumulative'&&<div className="flow-range-controls"><label className="field"><span>累計起點 · 自期初起分鐘</span><Input type="number" min={0} max={minute} step="any" value={rangeStart} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)){setPlaying(false);setRangeStart(Math.max(0,Math.min(minute,value)));}}}/></label><div className="flow-actions"><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setRangeStart(0);}}>期初至目前</Button><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setRangeStart(0);setMinute(horizon);}}>完整期間</Button></div><p>拖動左端設定起點、右端設定終點。電量累計於同一區間；電池艙 SOC 顯示終點狀態。</p></div>}
   {mode==='cumulative'?<Slider aria-label="累計區間（起點與終點分鐘）" min={0} max={horizon} step={.01} minStepsBetweenThumbs={0} value={[rangeStart,minute]} onValueChange={([from,to])=>{setPlaying(false);setRangeStart(from);setMinute(to);}}/>:<Slider aria-label="模擬時間軸（分鐘）" aria-valuetext={flowTime(minute)} min={0} max={horizon} step={.01} value={[minute]} onValueChange={([value])=>changeTime(value)}/>}
   <div className="flow-daymarks">{Array.from({length:project.horizonDays+1},(_,day)=><button key={day} onClick={()=>changeTime(day*1440)} title={`第 ${day+1} 天起點`}>{day===project.horizonDays?'期末':`D${day+1}`}</button>)}</div>
   <p className="flow-interval" title={`精確區間 [${view.from}, ${view.to}) 分鐘`}>{view.available?`${flowTime(view.from)} ≤ t < ${flowTime(view.to)}${mode==='cumulative'?'：顯示起點至終點的累計電量，按實際功率區間積分。':mode==='power'?(result.detailedResult?'：線路端口功率在此區間固定；儲能自放電與庫存按目前時刻精確求值。':'：此區間功率保持不變；箭頭按實際供電方向。'):'：顯示整個小時的累積電量，不是此刻功率。'}`:'執行受限模擬後，拖動滑桿即可即時更新。'}{mode!=='cumulative'&&minute===horizon&&' 期末功率顯示結束前左極限；電池艙 SOC 顯示期末庫存狀態。'}{mode==='cumulative'&&rangeStart===minute&&' 起訖相同，累計電量為 0。'}</p>
  </div>
  {result.detailedResult?<DetailedFlowSummary result={result} view={view}/>:<FlowSummary view={view}/>}
  <div className="flow-workspace"><div className="flow-map-panel">
   <div className="flow-map-tools"><Choice label="圖面排列" value={arrangement} onChange={value=>{setArrangement(value);setCamera(null);}} options={[["reference","依原圖排列"],["saved","依設計位置"]]}/><div className="flow-actions"><Button size="sm" variant="outline" onClick={()=>setCamera(null)}><Maximize size={15}/>全圖</Button>{(['A','B'] as const).map(s=><Button key={s} size="sm" variant="outline" onClick={()=>{const group=layout.filter(n=>n.station===s);if(!group.length)return;const x=Math.min(...group.map(n=>n.x))-45,y=Math.min(...group.map(n=>n.y))-65,w=Math.max(...group.map(n=>n.x+W))-x+45;setCamera({x,y,w,h:w/RATIO});}}>{s} 區供電</Button>)}<Button size="icon" variant="ghost" aria-label="放大連接圖" onClick={()=>zoom(.75)}><ZoomIn size={17}/></Button><Button size="icon" variant="ghost" aria-label="縮小連接圖" onClick={()=>zoom(1/.75)}><ZoomOut size={17}/></Button><Button size="sm" variant="ghost" disabled={!device} onClick={()=>focus(selected)}><Focus size={15}/>定位所選</Button></div><label className="flow-switch"><Switch checked={labels} onCheckedChange={setLabels}/>全部線值</label></div>
   <div className="flow-search"><Search size={16}/><Input aria-label="搜尋並定位元件" placeholder="搜尋設備名稱或 ID，例如 B-gun" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<div className="flow-search-results">{matches.length?matches.slice(0,15).map(n=><button key={n.id} onClick={()=>{focus(n.id);setQuery('');}}>{n.station} 區 · {n.name}<small>{n.id}</small></button>):<p>找不到元件</p>}{matches.length>15&&<p>共 {matches.length} 項，請縮小搜尋範圍。</p>}</div>}</div>
   <svg ref={svg} className="flow-canvas" viewBox={`${box.x} ${box.y} ${box.w} ${box.h}`} aria-label={`完整連接圖：${layout.length} 個節點，${view.edges.length} 條連線`} onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;drag.current={x:e.clientX,y:e.clientY,box};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current||!svg.current)return;const r=svg.current.getBoundingClientRect(),scale=1/Math.min(r.width/drag.current.box.w,r.height/drag.current.box.h);setCamera({...drag.current.box,x:drag.current.box.x-(e.clientX-drag.current.x)*scale,y:drag.current.box.y-(e.clientY-drag.current.y)*scale});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <defs>{['AC','DC','off'].map(domain=><marker key={domain} id={`${prefix}-${domain}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0 L8,4 L0,8 Z" fill={domain==='AC'?'#dc514b':domain==='DC'?'#1684b5':'#9da8ac'}/></marker>)}</defs>
    {arrangement==='reference'&&<ReferenceBackdrop nodes={layout}/>}
    {view.edges.map(e=>{const a=nodeMap.get(e.source),b=nodeMap.get(e.target);if(!a||!b)return null;const wire=referenceWire(a,b),active=e.source===selected||e.target===selected,color=e.off||!view.available||e.value===0?'#9da8ac':e.domain==='AC'?'#dc514b':'#1684b5',path=wire.path;return <g key={e.id} data-edge={e.id}><title>{`${e.id}: ${display(e.value)} ${view.unit}`}</title><path d={path} fill="none" stroke={color} strokeWidth={(active?1:0)+(e.value>0?2+Math.min(3,Math.log10(e.value+1)*.6):1.2)} opacity={active?1:e.value>0?.8:.45} strokeDasharray={e.off?'7 5':undefined} markerEnd={`url(#${prefix}-${e.off||!view.available||e.value===0?'off':e.domain})`}/>{(labels||active)&&<text x={wire.x} y={wire.y} className="flow-wire-value" fill={color}>{display(e.value)} {view.unit}</text>}</g>;})}
    {layout.map(n=>{const f=values.get(n.id)!,rack=isBatteryRack(n),battery=rackStates.get(n.id);return <g key={n.id} data-node={n.id} transform={`translate(${n.x},${n.y})`} className={`flow-node ${selected===n.id?'is-selected':''} state-${f.status}`} role="button" tabIndex={0} aria-label={`${n.station} 區 ${n.name}，輸入 ${display(f.input)}，輸出 ${display(f.output)} ${view.unit}，${statusLabel(f)}${rack?`，${mode==='cumulative'?'終點 ':''}SOC ${battery?`${fmt(battery.soc*100,2)}%，${BATTERY_STATUS[battery.status]}`:'尚無記錄'}`:''}`} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n.id);}}}>
     <rect className="flow-node-card" width={W} height={H} rx="10"/><g transform="translate(12,13)"><EquipmentGlyph type={n.type} size={23}/></g><text x="44" y="28" className="flow-node-name">{n.name.length>15?`${n.name.slice(0,14)}…`:n.name}</text><text x="13" y="49" className="flow-node-id">{n.id}</text><text x="13" y="74">輸入 <tspan x="236" textAnchor="end">{display(f.input)} {view.unit}</tspan></text><text x="13" y="97">輸出 <tspan x="236" textAnchor="end">{display(f.output)} {view.unit}</tspan></text><text x="13" y="120">損耗 <tspan x="236" textAnchor="end">{display(f.loss)} {view.unit}</tspan></text>{rack?<><text x="13" y="139" className="flow-node-soc">{mode==='cumulative'?'終點 ':''}SOC {battery?`${fmt(battery.soc*100,2)}%`:'—'}</text><text x="236" y="139" textAnchor="end" className="flow-node-status">{battery?BATTERY_STATUS[battery.status]:'尚無 SOC 記錄'}</text></>:<text x="13" y="139" className="flow-node-status">{statusLabel(f)}</text>}<title>{`${n.name} · ${n.id}${battery?` · ${flowTime(minute)} SOC ${precise(battery.soc*100)}% · ${BATTERY_STATUS[battery.status]} · 庫存 ${precise(battery.energyKWh)} kWh · 電池 ${battery.batteryId}`:''}`}</title>
    </g>;})}
   </svg><div className="flow-legend"><span className="ac">━ AC 交流</span><span className="dc">━ DC 直流</span><span>灰線：零值 / 未計算 · 虛線：停用 / 閉鎖</span><span>放大讀數 · 拖曳空白處平移 · 點節點驗算 · 線路交叉不代表連接</span></div>
  </div><aside className="flow-inspector" aria-label="節點驗算明細">
   {node&&device?<><div className="flow-inspector-heading"><EquipmentGlyph type={device.type} size={28}/><div><span className="eyebrow">{device.station} 區 · 節點驗算</span><h3>{device.name}</h3><p>{device.id}</p></div></div><span className={`flow-status state-${node.status}`}>{statusLabel(node)}</span>
    {isBatteryRack(device)&&<BatterySOCPanel state={selectedBattery} minute={minute} mode={mode}/>}
    <dl className="flow-node-metrics">{[['輸入',node.input],['輸出',node.output],['損耗',node.loss],['末端吸收',node.terminal]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{display(value as number)} <small>{view.unit}</small></dd></div>)}</dl>
    {view.available&&<><div className={`flow-equation ${Math.max(Math.abs(node.conversionResidual),Math.abs(node.branchResidual),Math.abs(node.connectionResidual))>1e-6?'has-error':''}`}><strong>逐項守恆 · {view.unit}</strong><p>輸入 − 輸出 − 損耗</p><code>{precise(node.input)} − {precise(node.output)} − {precise(node.loss)}</code><b>殘差 {node.conversionResidual.toExponential(4)}</b><p>輸出 − 出線合計 − 末端吸收</p><code>{precise(node.output)} − {precise(node.outgoing)} − {precise(node.terminal)}</code><b>殘差 {node.branchResidual.toExponential(4)}</b>{!isFlowSourceType(device.type)?<><p>輸入 − 入線合計</p><code>{precise(node.input)} − {precise(node.incoming)}</code><b>殘差 {node.connectionResidual.toExponential(4)}</b></>:<p>{device.type==='grid'?'電網輸入來自外部電源，對應實體源端電表。':device.type==='pv-source'?'光伏來源是實際採收的直流發電；MPPT 與外售轉換損耗在下游元件記錄。':'此為 ESS／UPS 內部儲能來源端，並非額外外部發電。庫存變化與自放電請核對上方儲能帳。'}</p>}<small>合格容差 ≤ 10⁻⁶ {view.unit}；計算使用未四捨五入值。</small></div>
     <div className="flow-capacity"><span>設備輸出容量</span><strong>{fmt(node.capacityKW,2)} kW</strong><span>{mode==='cumulative'?'區間峰值':mode==='power'?'此刻輸出':'本小時峰值'}</span><strong>{fmt(node.peakKW,2)} kW</strong>{node.requested!==null&&node.requested>0&&<><span>末端要求功率</span><strong>{fmt(node.requested,2)} kW</strong></>}</div>
    </>}
    <h4>連接明細 · {view.unit}</h4><div className="flow-links">{links.map(e=><button key={e.id} onClick={()=>focus(e.source===selected?e.target:e.source)}><span>{e.target===selected?'入 ←':'出 →'} {nodeMap.get(e.source===selected?e.target:e.source)?.name}<small>{e.id}</small></span><strong>{display(e.value)}</strong></button>)}{!links.length&&<p>此節點沒有連線。</p>}</div>
    {view.available&&hourNode&&<details className="flow-hour-check"><summary>{mode==='cumulative'?'另查終點所在小時帳本':'對照此小時電量帳本'}</summary>{mode==='cumulative'&&<p>以下僅為終點所在小時的對照，非整段累計。</p>}<p>{flowTime(hourView.from)} — {flowTime(hourView.to)}</p>{(['input','output','loss','terminal'] as const).map((field,i)=>{const signal=result.powerTrace?.nodes.find(n=>n.nodeId===selected);return <div key={field}><strong>{['輸入','輸出','損耗','末端吸收'][i]}</strong><span>帳本 {precise(hourNode[field])} kWh</span>{signal&&<span>功率積分 {precise(integrateSignal(signal.samples,i+1,hourView.from,hourView.to,horizon))} kWh</span>}</div>;})}</details>}
    <NodeNote device={device} project={project}/>
    <Button variant="outline" className="flow-export" disabled={!view.available} onClick={()=>downloadFrame(result,view)}><ArrowDownToLine size={15}/>匯出全圖數值 JSON</Button><p className="flow-small">包含全部節點、連線、起訖時刻、游標時刻的電池艙狀態與參數快照；保留完整數值精度。</p>
   </>:<p>選取圖上的任一節點查看明細。</p>}
  </aside></div>
  <p className="flow-footnote">資料來自同一次受限模擬的逐事件分配記錄。零功率僅表示沒有能量流，不能據此判定設備是否帶電。守恆通過驗證的是數學一致性；設備參數、需求與獲利仍須以實測資料校準。</p>
 </section>;
}
export function BatterySOCPanel({state,minute,mode}:{state:BatteryCursorState|null;minute:number;mode:FlowMode}){
 const label=mode==='cumulative'?'終點 SOC':'此刻 SOC';
 if(!state)return <section className="flow-battery-state is-unavailable" aria-label="電池艙充電狀態"><strong>{label} —</strong><p>此結果沒有此電池艙的 SOC 記錄。請使用完整站務模型重新執行測算；「—」不代表電池為空。</p></section>;
 const percent=fmt(state.soc*100,2);
 return <section className="flow-battery-state" aria-label="電池艙充電狀態"><div className="flow-battery-heading"><div><span>{label}</span><strong>{percent}<small>%</small></strong></div><span className={`flow-battery-badge state-${state.status}`}>{BATTERY_STATUS[state.status]}</span></div><div className="flow-battery-meter" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={state.soc*100} aria-valuetext={`${percent}%，${BATTERY_STATUS[state.status]}`}><span style={{width:`${Math.max(0,Math.min(100,state.soc*100))}%`}}/></div><p className="flow-battery-time">{flowTime(minute)} · {mode==='cumulative'?'累計終點的庫存狀態':'游標時刻的庫存狀態'}</p><dl className="flow-battery-metrics">{([['庫存電量',state.energyKWh,'kWh'],['距離目標還需',state.remainingKWh,'kWh'],['電池端輸入',state.inputKW,'kW'],['實際入庫功率',state.storedKW,'kW'],['目標 SOC',state.readySOC*100,'%'],['有效容量',state.effectiveCapacityKWh,'kWh']] as const).map(([name,value,unit])=><div key={name}><dt>{name}</dt><dd title={precise(value)}>{fmt(value,2)} <small>{unit}</small></dd></div>)}</dl><dl className="flow-battery-identity"><div><dt>目前電池</dt><dd>{state.batteryId}</dd></div><div><dt>電池規格</dt><dd>{state.family}</dd></div><div><dt>健康度 SOH</dt><dd>{fmt(state.soh*100,2)}%</dd></div></dl><p className="flow-battery-note">SOC 是此刻電池的充電比例，kWh 是已儲存及待補的電量，kW 是此刻充電速度。切換每小時或累計電量時，SOC 仍顯示游標時刻，不做累加。換電完成時顯示換入電池；換出電池的能量另記於服務交付帳。</p></section>;
}
function NodeNote({device,project}:{device:Equipment;project:Project}){const model=project.detailed?.physics.find(m=>m.nodeId===device.id);let text='';if(['rack','passenger-rack','charger'].includes(device.type))text='末端吸收表示電池入庫補電或車輛充電。換電交付是電池庫存移轉，請另核對營運帳，不能在供電線上再次扣電。';if(device.type.includes('cable'))text=model?.cable.enabled?'此電纜依已保存的電阻、長度、電流、溫度與限值計算壓降及損耗；圖面值來自同一次實際分配。':'此電纜目前採理想模型；欲計算 I²R 及壓降，請填入並啟用單台電纜模型後重算。';if(device.type==='compensation')text=model?.compensation.enabled?'已啟用參數化無功補償與有功損耗；不代表現場完整 AC 潮流／保護認證。':'此補償節點未啟用無功模型；目前不計補償效果。';if(device.type==='passenger')text='此站目前使用交流負載模式；乘用車完整服務需先填入並啟用站務參數。';if(device.type==='passenger-station')text='此乘用車站已啟用逐車換電、電池庫存、回充及服務收入；充電與站用各有獨立下游末端。';if(device.type==='storage-sink')text='此末端是 ESS／UPS 儲能入庫，屬內部移轉；全站邊界已用儲能庫存變化取代，未重複計為服務交付。';if(device.type==='grid-export')text='此末端為實際外售電量表。與購電分列，前級 MPPT、線路及外售轉換損耗均各計一次。';return text?<p className="flow-device-note">{text}</p>:null;}


export function FlowSummary({view}:{view:FlowView}){const cumulative=view.mode==='cumulative';return <div className="flow-summary">{[[cumulative?'累計總輸入（電網）':'電網總輸入',view.grid],[cumulative?'累計總輸出（末端）':'末端吸收',view.terminal],[cumulative?'累計總損耗':'設備損耗',view.loss],['最大守恆殘差',view.maxResidual]].map(([label,value])=><div key={label}><span>{label}</span><strong>{view.available?label==='最大守恆殘差'?(value as number).toExponential(2):fmt(value as number,2):'—'} <small>{view.unit}</small></strong></div>)}<p>{cumulative&&'總輸出採末端吸收，避免中間設備逐級加總而重複計量。'}末端吸收包含電池回充、車輛直充與輔助用電；換電交付屬庫存移轉，另見站務結果。</p></div>;}
