"use client";
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ChevronLeft, ChevronRight, Focus, Maximize, Pause, Play, Search, ZoomIn, ZoomOut } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Slider } from '../ui/slider';
import { Switch } from '../ui/switch';
import { Choice, fmt } from './controls';
import { EquipmentGlyph } from './facility';
import { flowView, integrateSignal, type FlowMode, type FlowNode, type FlowView } from '../../packages/power-trace/index.ts';
import type { Equipment, RunResult } from '../../packages/contracts/index.ts';
import './flow-explorer.css';

const STATUS:Record<FlowNode['status'],string>={off:'停用 / 預留',interlock:'輔助供電閉鎖',shortfall:'輔助供電不足',mixed:'此區間狀態有變',limited:'供給受限',idle:'零功率',flow:'有能量流',unmodeled:'無功未建模',unknown:'未計算',empty:'空區間'};
const W=250,H=148,RATIO=1.6;
type Box={x:number;y:number;w:number;h:number};
export function flowTime(minute:number){const milliseconds=Math.round(minute*60000),day=Math.floor(milliseconds/86400000),within=milliseconds%86400000;return `D${day+1} ${String(Math.floor(within/3600000)).padStart(2,'0')}:${String(Math.floor(within/60000)%60).padStart(2,'0')}:${(within%60000/1000).toFixed(3).padStart(6,'0')}`;}
function bounds(nodes:{x:number;y:number}[]):Box{const x=Math.min(...(nodes.length?nodes.map(n=>n.x):[0]))-45,y=Math.min(...(nodes.length?nodes.map(n=>n.y):[0]))-65,w=Math.max(600,...nodes.map(n=>n.x+W))-x+45,h=Math.max(400,...nodes.map(n=>n.y+H))-y+45;return {x,y,w:Math.max(w,h*RATIO),h:Math.max(h,w/RATIO)};}
function precise(n:number){return Number.isFinite(n)?String(Number(n.toPrecision(13))):'—';}
function downloadFrame(result:RunResult,view:FlowView){const data={engineVersion:result.engineVersion,parameterSnapshot:result.parameterSnapshot,selection:{minute:view.minute,from:view.from,to:view.to,mode:view.mode,unit:view.unit},nodes:view.nodes,edges:view.edges,conservation:{grid:view.grid,terminal:view.terminal,loss:view.loss,maxResidual:view.maxResidual},systemBoundary:{input:view.grid,output:view.terminal,loss:view.loss,unit:view.unit,outputDefinition:'Terminal absorption; intermediate transfers excluded'}};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`HighwaySwapSim-flow-${view.mode}-${view.from}-${view.to}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function FlowExplorer({result,busy=false,onRunCurrent,onRunDemo}:{result:RunResult;busy?:boolean;onRunCurrent?:()=>void;onRunDemo?:()=>void}){
 const [minute,setMinute]=useState(0),[mode,setMode]=useState<FlowMode>('power'),[rangeStart,setRangeStart]=useState(0),[selected,setSelected]=useState(result.parameterSnapshot.topology.nodes[0]?.id??''),[playing,setPlaying]=useState(false),[labels,setLabels]=useState(false),[query,setQuery]=useState('');
 const project=result.parameterSnapshot,horizon=project.horizonDays*1440;
 const layout=useMemo(()=>project.topology.nodes.map(n=>({...n,x:n.x*1.45,y:n.y*1.95})),[project]);
 const full=useMemo(()=>bounds(layout),[layout]),[camera,setCamera]=useState<Box|null>(null),box=camera??full;
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;box:Box}|null>(null),prefix=useId().replace(/:/g,'');
 const hourMinute=Math.min(Math.floor(minute/60),horizon/60-1)*60;
 const hourView=useMemo(()=>flowView(result,hourMinute,'energy'),[result,hourMinute]);
 const view=useMemo(()=>mode==='energy'?({...hourView,minute}):flowView(result,minute,mode,rangeStart),[result,minute,mode,rangeStart,hourView]);
 const nodeMap=useMemo(()=>new Map(layout.map(n=>[n.id,n])),[layout]),values=new Map(view.nodes.map(n=>[n.id,n]));
 const device=nodeMap.get(selected),node=values.get(selected),hourNode=hourView.nodes.find(n=>n.id===selected);
 const events=useMemo(()=>mode==='energy'?Array.from({length:project.horizonDays*24+1},(_,i)=>i*60):[...result.powerTrace?.eventMinutes??[],horizon],[result,mode,horizon,project.horizonDays]);
 useEffect(()=>{setMinute(0);setRangeStart(0);setPlaying(false);setCamera(null);setSelected(result.parameterSnapshot.topology.nodes[0]?.id??'');},[result]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setMinute(current=>{const next=events.find(t=>t>current);if(next===undefined||next>=horizon){setPlaying(false);return horizon;}return next;}),650);return ()=>clearInterval(timer);},[playing,events,horizon]);
 function changeTime(t:number){setPlaying(false);setMinute(Math.max(mode==='cumulative'?rangeStart:0,Math.min(horizon,t)));}
 function jump(direction:number){changeTime(direction>0?events.find(t=>t>minute)??horizon:events.filter(t=>t<minute).at(-1)??0);}
 function zoom(factor:number){setCamera(old=>{const b=old??full,w=Math.max(500,Math.min(full.w*2,b.w*factor));return {x:b.x+(b.w-w)/2,y:b.y+(b.h-w/RATIO)/2,w,h:w/RATIO};});}
 function focus(id:string){const n=nodeMap.get(id);if(!n)return;setSelected(id);setCamera({x:n.x+W/2-550,y:n.y+H/2-550/RATIO,w:1100,h:1100/RATIO});}
 const display=(value:number)=>view.available?fmt(value,2):'—';
 const statusLabel=(n:FlowNode)=>mode==='power'?STATUS[n.status]:n.status==='idle'?'區間零電量':STATUS[n.status];
 const links=view.edges.filter(e=>e.source===selected||e.target===selected),matches=layout.filter(n=>`${n.station} ${n.name} ${n.id}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="flow-explorer" aria-label="能量流驗算">
  <div className="flow-heading"><div><p className="eyebrow">ENERGY FLOW EXPLORER</p><h2>沿著每一條線，核對每一度電。</h2><p>完整連接圖 · {layout.length} 個節點 / {view.edges.length} 條連線 · 結果快照：{project.name}</p></div><div className="flow-actions">{onRunCurrent&&<Button disabled={busy} variant="outline" onClick={onRunCurrent}>執行目前受限參數</Button>}{onRunDemo&&<Button disabled={busy} onClick={onRunDemo}><Play size={16}/>完整設備案例 · 3 天</Button>}</div></div>
  {!view.available&&<div className="flow-unavailable" role="status"><strong>尚無可驗算的功率記錄</strong><p>{result.mode==='SOURCE_REPLAY'?'來源原表重播沒有模擬節點功率。請執行受限參數，或載入右上方的 3 天完整設備案例。':'此結果未保存事件功率記錄，請重新執行測算；仍可切換每小時電量。'}「—」表示未計算，並非零功率。</p></div>}
  <div className="flow-timeline">
   <div className="flow-time-top"><div><span className="eyebrow">{mode==='cumulative'?'區間累計 · kWh':mode==='power'?'事件功率 · 不插值':'整小時積分電量'}</span><strong className={`flow-clock ${mode==='cumulative'?'is-range':''}`} aria-live="polite">{mode==='cumulative'&&`${flowTime(rangeStart)} → `}{flowTime(minute)}{mode!=='cumulative'&&minute===horizon?' · 期末左極限':''}</strong></div><Choice label="圖面數值" value={mode} onChange={value=>{setMode(value as FlowMode);setPlaying(false);if(value==='cumulative'){const end=minute===0?horizon:minute;setRangeStart(Math.min(rangeStart,end));setMinute(end);}}} options={[["power","當下功率 kW"],["energy","每小時電量 kWh"],["cumulative","區間累計 kWh"]]}/><label className="field"><span>{mode==='cumulative'?'累計終點 · 自期初起分鐘':'精確時間 · 自期初起分鐘'}</span><Input type="number" min={mode==='cumulative'?rangeStart:0} max={horizon} step="any" value={minute} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))changeTime(n);}}/></label><div className="flow-play"><Button variant="outline" size="icon" aria-label="上一個變化時刻" disabled={!view.available||minute===(mode==='cumulative'?rangeStart:0)} onClick={()=>jump(-1)}><ChevronLeft size={18}/></Button><Button variant="outline" size="icon" aria-label={playing?'暫停時間軸':'播放時間軸'} disabled={!view.available} onClick={()=>{if(minute>=horizon)setMinute(mode==='cumulative'?rangeStart:0);setPlaying(!playing);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</Button><Button variant="outline" size="icon" aria-label="下一個變化時刻" disabled={!view.available||minute===horizon} onClick={()=>jump(1)}><ChevronRight size={18}/></Button></div></div>
   {mode==='cumulative'&&<div className="flow-range-controls"><label className="field"><span>累計起點 · 自期初起分鐘</span><Input type="number" min={0} max={minute} step="any" value={rangeStart} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)){setPlaying(false);setRangeStart(Math.max(0,Math.min(minute,value)));}}}/></label><div className="flow-actions"><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setRangeStart(0);}}>期初至目前</Button><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setRangeStart(0);setMinute(horizon);}}>完整期間</Button></div><p>拖動左端設定起點、右端設定終點。所有讀數累計於同一區間。</p></div>}
   {mode==='cumulative'?<Slider aria-label="累計區間（起點與終點分鐘）" min={0} max={horizon} step={.01} minStepsBetweenThumbs={0} value={[rangeStart,minute]} onValueChange={([from,to])=>{setPlaying(false);setRangeStart(from);setMinute(to);}}/>:<Slider aria-label="模擬時間軸（分鐘）" aria-valuetext={flowTime(minute)} min={0} max={horizon} step={.01} value={[minute]} onValueChange={([value])=>changeTime(value)}/>}
   <div className="flow-daymarks">{Array.from({length:project.horizonDays+1},(_,day)=><button key={day} onClick={()=>changeTime(day*1440)} title={`第 ${day+1} 天起點`}>{day===project.horizonDays?'期末':`D${day+1}`}</button>)}</div>
   <p className="flow-interval" title={`精確區間 [${view.from}, ${view.to}) 分鐘`}>{view.available?`${flowTime(view.from)} ≤ t < ${flowTime(view.to)}${mode==='cumulative'?'：顯示起點至終點的累計電量，按實際功率區間積分。':mode==='power'?'：此區間功率保持不變；箭頭按實際供電方向。':'：顯示整個小時的累積電量，不是此刻功率。'}`:'執行受限模擬後，拖動滑桿即可即時更新。'}{mode!=='cumulative'&&minute===horizon&&' 期末只顯示模擬結束前的最後狀態。'}{mode==='cumulative'&&rangeStart===minute&&' 起訖相同，累計電量為 0。'}</p>
  </div>
  <FlowSummary view={view}/>
  <div className="flow-workspace"><div className="flow-map-panel">
   <div className="flow-map-tools"><div className="flow-actions"><Button size="sm" variant="outline" onClick={()=>setCamera(null)}><Maximize size={15}/>全圖</Button>{(['A','B'] as const).map(s=><Button key={s} size="sm" variant="outline" onClick={()=>{const group=layout.filter(n=>n.station===s);if(!group.length)return;const x=Math.min(...group.map(n=>n.x))-45,y=Math.min(...group.map(n=>n.y))-65,w=Math.max(...group.map(n=>n.x+W))-x+45;setCamera({x,y,w,h:w/RATIO});}}>{s} 區供電</Button>)}<Button size="icon" variant="ghost" aria-label="放大連接圖" onClick={()=>zoom(.75)}><ZoomIn size={17}/></Button><Button size="icon" variant="ghost" aria-label="縮小連接圖" onClick={()=>zoom(1/.75)}><ZoomOut size={17}/></Button><Button size="sm" variant="ghost" disabled={!device} onClick={()=>focus(selected)}><Focus size={15}/>定位所選</Button></div><label className="flow-switch"><Switch checked={labels} onCheckedChange={setLabels}/>全部線值</label></div>
   <div className="flow-search"><Search size={16}/><Input aria-label="搜尋並定位元件" placeholder="搜尋設備名稱或 ID，例如 B-gun" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<div className="flow-search-results">{matches.length?matches.slice(0,15).map(n=><button key={n.id} onClick={()=>{focus(n.id);setQuery('');}}>{n.station} 區 · {n.name}<small>{n.id}</small></button>):<p>找不到元件</p>}{matches.length>15&&<p>共 {matches.length} 項，請縮小搜尋範圍。</p>}</div>}</div>
   <svg ref={svg} className="flow-canvas" viewBox={`${box.x} ${box.y} ${box.w} ${box.h}`} aria-label={`完整連接圖：${layout.length} 個節點，${view.edges.length} 條連線`} onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;drag.current={x:e.clientX,y:e.clientY,box};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current||!svg.current)return;const r=svg.current.getBoundingClientRect(),scale=1/Math.min(r.width/drag.current.box.w,r.height/drag.current.box.h);setCamera({...drag.current.box,x:drag.current.box.x-(e.clientX-drag.current.x)*scale,y:drag.current.box.y-(e.clientY-drag.current.y)*scale});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <defs>{['AC','DC','off'].map(domain=><marker key={domain} id={`${prefix}-${domain}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0 L8,4 L0,8 Z" fill={domain==='AC'?'#dc514b':domain==='DC'?'#1684b5':'#9da8ac'}/></marker>)}</defs>
    {(['A','B'] as const).map(s=>{const group=layout.filter(n=>n.station===s);if(!group.length)return null;return <text key={s} x={Math.min(...group.map(n=>n.x))} y={Math.min(...group.map(n=>n.y))-25} className="flow-area-label">服務區 {s}</text>;})}
    {view.edges.map(e=>{const a=nodeMap.get(e.source),b=nodeMap.get(e.target);if(!a||!b)return null;const horizontal=Math.abs(a.y-b.y)<H,forward=b.x>a.x,ax=horizontal?a.x+(forward?W:0):a.x+W/2,ay=horizontal?a.y+H/2:a.y+(b.y>a.y?H:0),bx=horizontal?b.x+(forward?0:W):b.x+W/2,by=horizontal?b.y+H/2:b.y+(b.y>a.y?0:H),mid=(ay+by)/2,active=e.source===selected||e.target===selected,color=e.off||!view.available||e.value===0?'#9da8ac':e.domain==='AC'?'#dc514b':'#1684b5',path=horizontal?`M${ax},${ay} H${(ax+bx)/2} V${by} H${bx}`:`M${ax},${ay} V${mid} H${bx} V${by}`;return <g key={e.id} data-edge={e.id}><title>{`${e.id}: ${display(e.value)} ${view.unit}`}</title><path d={path} fill="none" stroke={color} strokeWidth={(active?1:0)+(e.value>0?2+Math.min(3,Math.log10(e.value+1)*.6):1.2)} opacity={active?1:e.value>0?.8:.45} strokeDasharray={e.off?'7 5':undefined} markerEnd={`url(#${prefix}-${e.off||!view.available||e.value===0?'off':e.domain})`}/>{(labels||active)&&<text x={(ax+bx)/2} y={(ay+by)/2-6} className="flow-wire-value" fill={color}>{display(e.value)} {view.unit}</text>}</g>;})}
    {layout.map(n=>{const f=values.get(n.id)!;return <g key={n.id} data-node={n.id} transform={`translate(${n.x},${n.y})`} className={`flow-node ${selected===n.id?'is-selected':''} state-${f.status}`} role="button" tabIndex={0} aria-label={`${n.station} 區 ${n.name}，輸入 ${display(f.input)}，輸出 ${display(f.output)} ${view.unit}，${statusLabel(f)}`} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n.id);}}}>
     <rect className="flow-node-card" width={W} height={H} rx="10"/><g transform="translate(12,13)"><EquipmentGlyph type={n.type} size={23}/></g><text x="44" y="28" className="flow-node-name">{n.name.length>15?`${n.name.slice(0,14)}…`:n.name}</text><text x="13" y="49" className="flow-node-id">{n.id}</text><text x="13" y="74">輸入 <tspan x="236" textAnchor="end">{display(f.input)} {view.unit}</tspan></text><text x="13" y="97">輸出 <tspan x="236" textAnchor="end">{display(f.output)} {view.unit}</tspan></text><text x="13" y="120">損耗 <tspan x="236" textAnchor="end">{display(f.loss)} {view.unit}</tspan></text><text x="13" y="139" className="flow-node-status">{statusLabel(f)}</text><title>{`${n.name} · ${n.id}`}</title>
    </g>;})}
   </svg><div className="flow-legend"><span className="ac">━ AC 交流</span><span className="dc">━ DC 直流</span><span>灰線：零值 / 未計算 · 虛線：停用 / 閉鎖</span><span>放大讀數 · 拖曳空白處平移 · 點節點驗算 · 線路交叉不代表連接</span></div>
  </div><aside className="flow-inspector" aria-label="節點驗算明細">
   {node&&device?<><div className="flow-inspector-heading"><EquipmentGlyph type={device.type} size={28}/><div><span className="eyebrow">{device.station} 區 · 節點驗算</span><h3>{device.name}</h3><p>{device.id}</p></div></div><span className={`flow-status state-${node.status}`}>{statusLabel(node)}</span>
    <dl className="flow-node-metrics">{[['輸入',node.input],['輸出',node.output],['損耗',node.loss],['末端吸收',node.terminal]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{display(value as number)} <small>{view.unit}</small></dd></div>)}</dl>
    {view.available&&<><div className={`flow-equation ${Math.max(Math.abs(node.conversionResidual),Math.abs(node.branchResidual),Math.abs(node.connectionResidual))>1e-6?'has-error':''}`}><strong>逐項守恆 · {view.unit}</strong><p>輸入 − 輸出 − 損耗</p><code>{precise(node.input)} − {precise(node.output)} − {precise(node.loss)}</code><b>殘差 {node.conversionResidual.toExponential(4)}</b><p>輸出 − 出線合計 − 末端吸收</p><code>{precise(node.output)} − {precise(node.outgoing)} − {precise(node.terminal)}</code><b>殘差 {node.branchResidual.toExponential(4)}</b>{device.type!=='grid'?<><p>輸入 − 入線合計</p><code>{precise(node.input)} − {precise(node.incoming)}</code><b>殘差 {node.connectionResidual.toExponential(4)}</b></>:<p>電網輸入來自外部電源，對應實體源端電表。</p>}<small>合格容差 ≤ 10⁻⁶ {view.unit}；計算使用未四捨五入值。</small></div>
     <div className="flow-capacity"><span>設備輸出容量</span><strong>{fmt(node.capacityKW,2)} kW</strong><span>{mode==='cumulative'?'區間峰值':mode==='power'?'此刻輸出':'本小時峰值'}</span><strong>{fmt(node.peakKW,2)} kW</strong>{node.requested!==null&&node.requested>0&&<><span>末端要求功率</span><strong>{fmt(node.requested,2)} kW</strong></>}</div>
    </>}
    <h4>連接明細 · {view.unit}</h4><div className="flow-links">{links.map(e=><button key={e.id} onClick={()=>focus(e.source===selected?e.target:e.source)}><span>{e.target===selected?'入 ←':'出 →'} {nodeMap.get(e.source===selected?e.target:e.source)?.name}<small>{e.id}</small></span><strong>{display(e.value)}</strong></button>)}{!links.length&&<p>此節點沒有連線。</p>}</div>
    {view.available&&hourNode&&<details className="flow-hour-check"><summary>{mode==='cumulative'?'另查終點所在小時帳本':'對照此小時電量帳本'}</summary>{mode==='cumulative'&&<p>以下僅為終點所在小時的對照，非整段累計。</p>}<p>{flowTime(hourView.from)} — {flowTime(hourView.to)}</p>{(['input','output','loss','terminal'] as const).map((field,i)=>{const signal=result.powerTrace?.nodes.find(n=>n.nodeId===selected);return <div key={field}><strong>{['輸入','輸出','損耗','末端吸收'][i]}</strong><span>帳本 {precise(hourNode[field])} kWh</span>{signal&&<span>功率積分 {precise(integrateSignal(signal.samples,i+1,hourView.from,hourView.to,horizon))} kWh</span>}</div>;})}</details>}
    <NodeNote device={device}/>
    <Button variant="outline" className="flow-export" disabled={!view.available} onClick={()=>downloadFrame(result,view)}><ArrowDownToLine size={15}/>匯出全圖數值 JSON</Button><p className="flow-small">包含全部節點、連線、起訖時刻與參數快照；保留完整數值精度。</p>
   </>:<p>選取圖上的任一節點查看明細。</p>}
  </aside></div>
  <p className="flow-footnote">資料來自同一次受限模擬的逐事件分配記錄。零功率僅表示沒有能量流，不能據此判定設備是否帶電。守恆通過驗證的是數學一致性；設備參數、需求與獲利仍須以實測資料校準。</p>
 </section>;
}
function NodeNote({device}:{device:Equipment}){let text='';if(device.type==='rack'||device.type==='charger')text='末端吸收表示電池回充或車輛充電。換電交付是電池庫存移轉，不會在這條供電線上再次扣電。';if(device.type.includes('cable'))text='目前線纜採理想模型，線損為 0；長度與容量仍保留於參數。';if(device.type==='compensation')text='功率補償櫃保留在完整拓撲中；無功潮流、電壓與功率因數補償效果尚未模擬。';if(device.type==='passenger')text='CATL 巧克力站此處以交流負載建模，尚無乘用車逐車換電、排隊及電池庫存模型。';return text?<p className="flow-device-note">{text}</p>:null;}

export function FlowSummary({view}:{view:FlowView}){const cumulative=view.mode==='cumulative';return <div className="flow-summary">{[[cumulative?'累計總輸入（電網）':'電網總輸入',view.grid],[cumulative?'累計總輸出（末端）':'末端吸收',view.terminal],[cumulative?'累計總損耗':'設備損耗',view.loss],['最大守恆殘差',view.maxResidual]].map(([label,value])=><div key={label}><span>{label}</span><strong>{view.available?label==='最大守恆殘差'?(value as number).toExponential(2):fmt(value as number,2):'—'} <small>{view.unit}</small></strong></div>)}<p>{cumulative&&'總輸出採末端吸收，避免中間設備逐級加總而重複計量。'}末端吸收包含電池回充、車輛直充與輔助用電；換電交付屬庫存移轉，另見站務結果。</p></div>;}
