"use client";
import {useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,Legend,CartesianGrid,LineChart,Line} from 'recharts';
import type {Project,RunResult} from '../../packages/contracts/index.ts';
import {ANNUAL_SOURCE,capacityMatches,capacitySummary,defaultLoadPlan,demandSummary,loadPlanOf,LOAD_LABELS,LOAD_LEVELS,planningCSV,projectTenYears,type CapacityRuns,type LoadLevel,type LoadPlan} from '../../packages/load-planning/index.ts';
import {loadPlanSchema} from '../../packages/load-planning/schema.ts';
import {Button} from '../ui/button';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '../ui/table';
import {Input} from '../ui/input';
import {Choice,NumberField,Stat,fmt} from './controls';
import './load-planning.css';
function download(name:string,data:string,type:string){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function LoadPlanningPanel({project,setProject,runs,busy,onRunAll,onInspect}:{project:Project;setProject:(p:Project)=>void;runs:CapacityRuns;busy:boolean;onRunAll:()=>void;onInspect:(r:RunResult)=>void}){
 const [error,setError]=useState(''),plan=loadPlanOf(project),estimate=projectTenYears(project,runs);
 const chart=estimate.rows.map(r=>({year:String(r.year),AC:r.acSalesKWh/10000,DC:r.dcSalesKWh/10000,年度節電收益:r.benefitCNY/10000,累計節電收益:r.cumulativeBenefitCNY/10000}));
 function change(next:LoadPlan){try{setProject({...project,loadPlan:loadPlanSchema.parse(next)});setError('');}catch{setError('請填入有效設定：效率大於0且不超過100%，營運日0–366，年度折算係數0–1000%。');}}
 function yearValue(index:number,key:'operatingDays'|'demandFactor'|'traditionalEfficiency'|'sstEfficiency',value:number){change({...plan,years:plan.years.map((r,i)=>i===index?{...r,[key]:value}:r)});}
 return <div className="plan-page">
  <section className="panel"><div className="panel-heading"><div><p className="eyebrow">TEN-YEAR OPERATING PLAN</p><h2>{plan.years[0].year}–{plan.years.at(-1)!.year} 十年營運估算</h2></div><div className="plan-toolbar"><Button variant="outline" onClick={()=>download('HighwaySwapSim-ten-year.csv',planningCSV(project,runs),'text/csv;charset=utf-8')}>匯出十年 CSV</Button><Button variant="outline" onClick={()=>download('HighwaySwapSim-ten-year-report.json',JSON.stringify({format:'HighwaySwapSim.TenYearReport',version:1,project,estimate,capacity:LOAD_LEVELS.map(level=>({level,status:capacityMatches(project,level,runs[level])?'current':runs[level]?'stale':'not-run',summary:capacityMatches(project,level,runs[level])?capacitySummary(runs[level]!):null}))},null,2),'application/json')}>匯出估算 JSON</Button></div></div>
   <p className="plan-note">由三種代表日推估逐年充換電需求，使用相同售電量比較傳統方案與 SST 的購電量。節電收益是能源成本差額；完整投資損益仍由「獲利能力」頁的資產、營運費及稅務設定計算。</p>
   <div className="stats-grid compact"><Stat label="十年充換電需求（AC＋DC）" value={fmt(estimate.totals.totalSalesKWh/10000,2)} unit="萬度"/><Stat label="SST／DC 售電需求" value={fmt(estimate.totals.dcSalesKWh/10000,2)} unit="萬度"/><Stat label="SST 預估節電" value={fmt(estimate.totals.savedKWh/10000,2)} unit="萬度"/><Stat label="預估節電收益" value={fmt(estimate.totals.benefitCNY/10000,2)} unit="萬元 CNY" note="未扣設備價差、維運、稅務；未折現"/></div>
   <div className="plan-chart-grid"><div><h3>年度需求組成</h3><div className="plan-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year" fontSize={12}/><YAxis width={55} fontSize={12}/><Tooltip formatter={(v)=>`${fmt(Number(v),2)} 萬度`}/><Legend/><Bar name="AC／PCS" dataKey="AC" stackId="energy" fill="#d5a34c"/><Bar name="DC／SST" dataKey="DC" stackId="energy" fill="#18826b"/></BarChart></ResponsiveContainer></div></div><div><h3>節電收益累積（萬元 CNY）</h3><div className="plan-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year" fontSize={12}/><YAxis width={50} fontSize={12}/><Tooltip formatter={(v)=>`${fmt(Number(v),2)} 萬元`}/><Legend/><Line type="linear" dataKey="年度節電收益" stroke="#73968d" strokeWidth={2}/><Line type="linear" dataKey="累計節電收益" stroke="#147c68" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></div>
  </section>
  <section className="panel"><h2>年度負載設計</h2><p className="plan-note">預設 2027 低負載、2028–2029 中負載、2030–2036 高負載。原圖同一負載有不同年售電量，因此以 365 日及來源 SST 年售電量反推「年度折算係數」。它是規劃折算值，可依實際營運天數調整；不代表設備容量利用率。</p>
   <div className="plan-toolbar"><NumberField label="節省每度電的價值" value={plan.energyValueCnyPerKWh} unit="CNY/kWh" max={100} onChange={v=>{if(v!==null)change({...plan,energyValueCnyPerKWh:v});}}/><Button variant="outline" onClick={()=>change({...plan,years:defaultLoadPlan().years,energyValueCnyPerKWh:.67})}>還原年度來源設計</Button></div>
   {error&&<p role="alert" className="notice error">{error}</p>}
   <div className="table-scroll plan-table-inputs"><Table><TableHeader><TableRow>{['年度','代表日劇本','營運天數','年度折算 %','傳統加權效率 %','SST加權效率 %','等效劇本日數','AC需求 萬度','DC需求 萬度','節電 萬度','節電收益 萬元'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{estimate.rows.map((r,i)=><TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell><Choice label={`${r.year} 負載`} value={r.load} onChange={v=>change({...plan,years:plan.years.map((y,j)=>j===i?{...y,load:v as LoadLevel}:y)})} options={LOAD_LEVELS.map(l=>[l,LOAD_LABELS[l]])}/></TableCell>{(['operatingDays','demandFactor','traditionalEfficiency','sstEfficiency'] as const).map(key=><TableCell key={key}><Input aria-label={`${r.year} ${key}`} type="number" step="any" value={key==='operatingDays'?r[key]:Number((r[key]*100).toFixed(8))} onChange={e=>{if(e.target.value===''){setError('設定不可留白');return;}yearValue(i,key,e.target.valueAsNumber/(key==='operatingDays'?1:100));}}/></TableCell>)}<TableCell className="plan-numeric">{fmt(r.equivalentDays,2)}</TableCell><TableCell className="plan-numeric">{fmt(r.acSalesKWh/10000,2)}</TableCell><TableCell className="plan-numeric">{fmt(r.dcSalesKWh/10000,2)}</TableCell><TableCell className="plan-numeric">{fmt(r.savedKWh/10000,2)}</TableCell><TableCell className="plan-numeric">{fmt(r.benefitCNY/10000,2)}</TableCell></TableRow>)}</TableBody></Table></div>
   <div className="plan-formula">年售電需求＝代表日需求 × 營運天數 × 年度折算係數。<br/>SST 節電量＝DC 年售電需求 ×（1／傳統加權效率 − 1／SST 加權效率）。<br/>節電收益＝節電量 × 每度電價值。已使用全流程加權效率，不再重乘單台設備效率；效率變差時會顯示負收益。</div>
  </section>
  <section className="panel"><div className="panel-heading"><h2>目前設備能否服務這些需求？</h2><Button disabled={busy||!project.detailed} onClick={onRunAll}>{busy?'測算執行中…':'驗證高・中・低設備能力'}</Button></div>
   <p className="plan-note">用目前電池艙配置、槍位、SOC、效率及第一天設備排程，分別執行三個代表日。其他已設定的負載與逐車事件會共同競爭供電；下表交付率只統計劇本的重卡充換電。設備或劇本修改後，舊結果標示待重算。</p>
   <div className="table-scroll"><Table><TableHeader><TableRow>{['劇本','需求 kWh/日','實際交付 kWh/日','未交付 kWh/日','交付率','期末庫存差 kWh','狀態／能量流'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{LOAD_LEVELS.map(level=>{const run=runs[level],fresh=capacityMatches(project,level,run),d=fresh?capacitySummary(run!):null;return <TableRow key={level}><TableCell>{LOAD_LABELS[level]}</TableCell><TableCell>{fmt(demandSummary(plan.profiles[level]).total.energyKWh)}</TableCell><TableCell>{d?fmt(d.deliveredKWh,2):'—'}</TableCell><TableCell>{d?fmt(d.unservedKWh,2):'—'}</TableCell><TableCell>{d?`${fmt(d.completionRatio*100,2)}%`:'—'}</TableCell><TableCell>{d?fmt(d.inventoryDeltaKWh,2):'—'}</TableCell><TableCell>{d?<><span className={!d.inventoryRestored?'pending':'fresh'}>{!d.inventoryRestored?'庫存未補回':'已完成代表日測算'}</span><Button size="sm" variant="ghost" onClick={()=>onInspect(run!)}>查看能量流</Button></>:<span className="pending">{run?'設定已變更，請重算':'尚未測算'}</span>}</TableCell></TableRow>;})}</TableBody></Table></div>
   <p className="plan-note">下表以代表日實際交付量折算全年，供設備瓶頸評估。期末庫存不足期初、或年度折算超過 100% 時，不外推容量驗證收益。全站購電與電量費含其他負載，隨目前設備效率重算；電量費不含需量費與固定費。這不是連續十年事件模擬，不含自動設備老化、擴建或電池壽命推定。</p>
   <div className="table-scroll"><Table><TableHeader><TableRow>{['年度','劇本','規劃總需求 萬度','可交付參考 萬度','未交付參考 萬度','容量限制後節電收益 萬元','全站購電參考 萬度','全站電量費參考 萬元','依據'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{estimate.rows.map(r=><TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell>{LOAD_LABELS[r.load]}</TableCell><TableCell>{fmt(r.totalSalesKWh/10000,2)}</TableCell><TableCell>{r.estimatedDeliverableKWh===null?'—':fmt(r.estimatedDeliverableKWh/10000,2)}</TableCell><TableCell>{r.estimatedUnservedKWh===null?'—':fmt(r.estimatedUnservedKWh/10000,2)}</TableCell><TableCell>{r.capacityLimitedBenefitCNY===null?'—':fmt(r.capacityLimitedBenefitCNY/10000,2)}</TableCell><TableCell>{r.estimatedSiteGridKWh===null?'—':fmt(r.estimatedSiteGridKWh/10000,2)}</TableCell><TableCell>{r.estimatedSiteEnergyCostCNY===null?'—':fmt(r.estimatedSiteEnergyCostCNY/10000,2)}</TableCell><TableCell>{{'not-run':'待驗證','stale':'待重算','inventory-depleted':'庫存未補回，停止外推','exceeds-reference':'負載超過代表日，需重設劇本','representative-day':'代表日折算'}[r.capacityStatus]}</TableCell></TableRow>)}</TableBody></Table></div>
  </section>
  <section className="panel"><details><summary>來源表對照、單位與差異</summary><p className="plan-note">年度圖未標單位，本頁按「萬度、萬元 CNY」解讀；節電價值預設 0.67 CNY/kWh，由來源節電量與增加收益比值推定。原圖效率只有小數點後兩位，部分效率差及節電量與顯示效率不完全一致；以下保留來源數字與本頁重新計算值，不補造隱藏公式。</p>
   <div className="table-scroll plan-source-table"><Table><TableHeader><TableRow>{['年度','原圖SST售電 萬度','原圖節電 萬度','本頁節電 萬度','差額 萬度','原圖增加收益 萬元','原圖效率差 %','依顯示效率差 百分點'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{estimate.rows.map(r=>{const source=ANNUAL_SOURCE.find(s=>s.year===r.year);return <TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell>{source?fmt(source.soldWanKWh,2):'—'}</TableCell><TableCell>{source?fmt(source.savedWanKWh,2):'—'}</TableCell><TableCell>{fmt(r.savedKWh/10000,4)}</TableCell><TableCell>{r.sourceSavedDeltaKWh===null?'—':fmt(r.sourceSavedDeltaKWh/10000,4)}</TableCell><TableCell>{source?fmt(source.benefitWanCNY,2):'—'}</TableCell><TableCell>{source?fmt(source.efficiencyDifferencePct,2):'—'}</TableCell><TableCell>{fmt(r.efficiencyDifferencePct,2)}</TableCell></TableRow>;})}</TableBody></Table></div>
   <p className="plan-note">逐時來源中 A 區 06 時換電服務費為 0.20，但來源總價仍為 0.78，與購電價 0.628011 相加不符。兩值均保留；「精確電價＋服務費」使用 0.828011，「來源總價」使用 0.78。年度節電價值獨立設定，不以服務售價代替購電成本。</p>
  </details></section>
 </div>;
}
