"use client";
import {useState} from 'react';
import {ResponsiveContainer,ComposedChart,Bar,Line,XAxis,YAxis,Tooltip,Legend,CartesianGrid} from 'recharts';
import type {Project,RunResult} from '../../packages/contracts/index.ts';
import {ANNUAL_SOURCE,capacityMatches,capacitySummary,planningDaySummary,defaultLoadPlan,loadPlanOf,LOAD_LEVELS,LOAD_LABELS,planningCSV,singleBusTenYears,type CapacityRuns,type LoadLevel,type LoadPlan} from '../../packages/load-planning/index.ts';
import {loadPlanSchema} from '../../packages/load-planning/schema.ts';
import {Button} from '../ui/button';
import {Input} from '../ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '../ui/table';
import {Choice,NumberField,Stat,fmt} from './controls';
import './load-planning.css';
type Props={project:Project;setProject:(p:Project)=>void;runs:CapacityRuns;busy:boolean;onRunAll:()=>void;onInspect:(r:RunResult)=>void};
const statusText:Record<string,string>={'ready':'能源收支估算','not-run':'待測算','stale':'參數已改，需重算','inventory-depleted':'庫存調整條件不符','idle-not-run':'背景用電待測算','idle-inventory-depleted':'背景日庫存不足','exceeds-reference':'超過代表日需求，需另建劇本'};
const wan=(v:number|null)=>v===null?'—':fmt(v/10000,2);
function download(name:string,content:string,mime:string){const url=URL.createObjectURL(new Blob([content],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function SingleBusPlanningPanel({project,setProject,runs,busy,onRunAll,onInspect}:Props){
 const [error,setError]=useState(''),plan=loadPlanOf(project),result=singleBusTenYears(project,runs),total=result.totals;
 const chart=result.rows.map(r=>({year:String(r.year),需求:r.demandKWh/10000,估計供應:r.deliveredKWh===null?null:r.deliveredKWh/10000,未完成:r.unservedKWh===null?null:r.unservedKWh/10000,累計能源後貢獻:r.cumulativeEnergyMarginCNY===null?null:r.cumulativeEnergyMarginCNY/10000}));
 function change(next:LoadPlan){try{setProject({...project,loadPlan:loadPlanSchema.parse(next)});setError('');}catch{setError('請填入合法數值；營運日0–366、年度折算係數0–1000%。超过100%須另建並驗算需求劇本。');}}
 function yearValue(index:number,key:'operatingDays'|'demandFactor',value:number){change({...plan,years:plan.years.map((y,i)=>i===index?{...y,[key]:value}:y)});}
 return <div className="plan-page">
  <section className="panel"><div className="panel-heading"><div><p className="eyebrow">PHASE 1 / TEN-YEAR CAPACITY</p><h2>{plan.years[0].year}–{plan.years.at(-1)!.year} 第一期設備營運估算</h2></div><Button disabled={busy} onClick={onRunAll}>{busy?'測算中…':'測算三種負載與背景用電'}</Button></div>
   <p className="plan-note">十年都使用目前同一套設備與設定：預設 A/B 各1台 SST、公共 DC 母線、每側3台 AC/DC＋5台 DC/DC。需求逐年變化，設備不自動擴充。修改設備效率、功率、排程或劇本後，需重新測算。</p>
   <div className="stats-grid compact"><Stat label="十年需求" value={wan(total.demandKWh)} unit="萬度"/><Stat label="估計可供應量" value={wan(total.deliveredKWh)} unit="萬度"/><Stat label="未完成需求" value={wan(total.unservedKWh)} unit="萬度"/><Stat label="十年能源後貢獻" value={wan(total.energyMarginCNY)} unit="萬元 CNY" note="售電收入－電量費；未扣設備、人力、維運及稅務"/></div>
   <div className="plan-chart-grid"><div><h3>需求與估計供應量（萬度）</h3><div className="plan-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis width={65}/><Tooltip formatter={v=>fmt(Number(v),2)}/><Legend/><Bar dataKey="估計供應" stackId="service" fill="#18826b"/><Bar dataKey="未完成" stackId="service" fill="#d5a34c"/><Line dataKey="需求" stroke="#465b74" dot={false}/></ComposedChart></ResponsiveContainer></div></div><div><h3>累計能源後貢獻（萬元 CNY）</h3><div className="plan-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis width={65}/><Tooltip formatter={v=>fmt(Number(v),2)}/><Line dataKey="累計能源後貢獻" stroke="#147c68" strokeWidth={3} connectNulls={false}/></ComposedChart></ResponsiveContainer></div></div></div>
   <div className="plan-toolbar"><Button variant="outline" onClick={()=>download('HighwaySwapSim-single-bus-ten-year.csv',planningCSV(project,runs),'text/csv;charset=utf-8')}>匯出十年 CSV</Button><Button variant="outline" onClick={()=>download('HighwaySwapSim-single-bus-ten-year.json',JSON.stringify({format:'HighwaySwapSim.SingleBusTenYears',version:1,project,result,capacity:LOAD_LEVELS.map(level=>({level,summary:capacityMatches(project,level,runs[level])?capacitySummary(runs[level]!):null}))},null,2),'application/json')}>匯出估算 JSON</Button></div>
  </section>
  <section className="panel"><h2>高、中、低：三日連續運轉與庫存調整</h2><p className="plan-note">各執行連續3天相同逐時劇本，下表顯示每日平均。外槍優先、AC／DC各組回充互斥。估計供應量扣除動用初始電池庫存的部分，換電收入按同支路平均單價扣回；原始能量流仍保留完整三天結果。</p><div className="table-scroll"><Table><TableHeader><TableRow>{['劇本','日均需求 kWh','調整後日均供應 kWh','日均缺口 kWh','供應率','扣除期初庫存 kWh/日','狀態'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{LOAD_LEVELS.map(level=>{const run=runs[level],fresh=capacityMatches(project,level,run),v=fresh?planningDaySummary(run!):null;return <TableRow key={level}><TableCell>{LOAD_LABELS[level]}</TableCell><TableCell>{v?fmt(v.requestedKWh,2):'—'}</TableCell><TableCell>{v?fmt(v.deliveredKWh,2):'—'}</TableCell><TableCell>{v?fmt(v.unservedKWh,2):'—'}</TableCell><TableCell>{v?`${fmt(v.completionRatio*100,2)}%`:'—'}</TableCell><TableCell>{v?fmt(v.stockConsumedKWh,2):'—'}</TableCell><TableCell>{v?<><span>{v.stockConsumedKWh>.01?'已扣除庫存消耗':'未動用期初庫存'}</span><Button variant="ghost" size="sm" onClick={()=>onInspect(run!)}>查看能量流</Button></>:run?'待重算':'待測算'}</TableCell></TableRow>;})}</TableBody></Table></div></section>
  <section className="panel"><h2>逐年需求與能源收支估算</h2><p className="plan-note">年度折算係數解讀為「代表日占營運日的比例」。其餘營運日仍保留背景負載與額外設定的服務，另行測算購電及收入。三天均值包含額外服務及施工事件原設定時間，不自動重複人工事件。預設沿用原圖年度需求，不沿用舊架構的效率作為新架構結果。</p>{error&&<p className="notice error" role="alert">{error}</p>}
   <div className="table-scroll plan-table-inputs"><Table><TableHeader><TableRow>{['年度','需求劇本','設備','營運日','代表日占比 %','需求 萬度','估計供應 萬度','缺口 萬度','購電 萬度','損耗 萬度','估計售電收入 萬元','電量費 萬元','能源後貢獻 萬元','依據'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{result.rows.map((r,i)=><TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell><Choice label={`${r.year} 負載`} value={r.load} onChange={v=>change({...plan,years:plan.years.map((y,j)=>j===i?{...y,load:v as LoadLevel}:y)})} options={LOAD_LEVELS.map(l=>[l,LOAD_LABELS[l]])}/></TableCell><TableCell>一期／{fmt(r.sstInstalledKW)} kW SST</TableCell><TableCell><Input aria-label={`${r.year} operatingDays`} type="number" min={0} max={366} value={r.operatingDays} onChange={e=>{if(e.target.value===''){setError('營運日不可留白');return;}yearValue(i,'operatingDays',e.target.valueAsNumber);}}/></TableCell><TableCell><Input aria-label={`${r.year} demandFactor`} type="number" step="any" value={Number((r.demandFactor*100).toFixed(8))} onChange={e=>{if(e.target.value===''){setError('占比不可留白');return;}yearValue(i,'demandFactor',e.target.valueAsNumber/100);}}/></TableCell>{[r.demandKWh,r.deliveredKWh,r.unservedKWh,r.gridKWh,r.lossKWh,r.revenueCNY,r.gridCostCNY,r.energyMarginCNY].map((v,j)=><TableCell className="plan-numeric" key={j}>{wan(v)}</TableCell>)}<TableCell>{statusText[r.status]}</TableCell></TableRow>)}</TableBody></Table></div>
   <p className="plan-formula">年度需求／估計供應＝三日測算日均值（供應扣除庫存消耗）× 營運日 × 代表日占比。<br/>年度購電／電量費／收入＝代表日數值 × 代表日數 ＋ 背景日數值 × 其餘營運日數。<br/>未完成需求視為當期缺口，未驗證跨日排隊可消化；三日平均不代表十年連續營運保證。未模擬設備自動擴充與電池老化；成本未齊不推定完整投資報酬。</p>
   <Button variant="outline" onClick={()=>change({...plan,years:defaultLoadPlan().years})}>還原年度需求設計</Button>
  </section>
  <section className="panel"><h2>同量售電的轉換效率比較</h2><p className="plan-note">使用目前箱變＋AC/DC 的額定加權效率作比較基準，與代表日 SST＋DC/DC 實際轉換效率比較同一筆估計供應 DC 售電量。只估轉換節电差額，不表示 AC 支路有能力接替全部 DC 需求；也不把此差額再加到上述能源後貢獻。</p>
   <NumberField label="節省每度電的價值" unit="CNY/kWh" value={plan.energyValueCnyPerKWh} min={0} max={100} onChange={v=>{if(v!==null)change({...plan,energyValueCnyPerKWh:v});}}/>
   <div className="table-scroll"><Table><TableHeader><TableRow>{['年度','AC路徑基準 %','DC實際轉換 %','轉換節電 萬度','節電價值 萬元'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{result.rows.map(r=><TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell>{r.acReferenceEfficiency===null?'—':fmt(r.acReferenceEfficiency*100,4)}</TableCell><TableCell>{r.sstConversionEfficiency===null?'—':fmt(r.sstConversionEfficiency*100,4)}</TableCell><TableCell>{wan(r.conversionSavedKWh)}</TableCell><TableCell>{wan(r.conversionSavingCNY)}</TableCell></TableRow>)}</TableBody></Table></div>
   <p className="plan-note">包含每台 AC/DC 效率調整；新預設 95.35% 不包含箱變損耗。啟用儲能、光伏、備援或非線性線損／效率模型後，這項簡化效率比較停用，營運購電與電量費仍按完整模型計算。</p>
  </section>
  <section className="panel"><details><summary>原圖年度參考數值</summary><p className="plan-note">保留來源供核對；原圖加權效率與增加收益屬於原方案，不當成新架構的測算結果。年度來源單位沿用「萬度／萬元CNY」假設。</p><div className="table-scroll"><Table><TableHeader><TableRow>{['年度','SST售電 萬度','原傳統效率 %','原SST效率 %','原節電 萬度','原增加收益 萬元'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{ANNUAL_SOURCE.map(r=><TableRow key={r.year}><TableCell>{r.year}</TableCell><TableCell>{r.soldWanKWh}</TableCell><TableCell>{fmt(r.traditionalEfficiency*100,2)}</TableCell><TableCell>{fmt(r.sstEfficiency*100,2)}</TableCell><TableCell>{r.savedWanKWh}</TableCell><TableCell>{r.benefitWanCNY}</TableCell></TableRow>)}</TableBody></Table></div></details></section>
 </div>;
}
